import type { IdeaProject } from '../types';

/**
 * Idea Lab — "Mycelium Robo-Tech", ADVANCED TIER (the flagship builds).
 *
 * House rules, identical to mycelium.ts, so the reader can trust every number:
 *  - (measured) = a published or directly measured figure, with a source below the project.
 *  - (modelled) = a first-order estimate this brief asks you to verify yourself.
 *  - (speculative) = a hypothesis or a cultural reading. It is never presented as established physics.
 *  - We never claim fungal consciousness, fungal "free energy", fungal navigation by magnetism, or
 *    silicon-class fungal computing. Where a claim is unproven we say so in realitySplit.narrative.
 *  - Mechanical, thermal and acoustic properties of mycelium biocomposites vary by an order of
 *    magnitude with species, substrate, particle size, moisture, pressing and drying. We quote ranges.
 */
export const myceliumAdvancedProjects: IdeaProject[] = [
  {
    id: 'myc-advanced-reservoir',
    title: 'Àgbá-Ìrònú — Mycelial Reservoir Computing Bench',
    tagline: 'Inject charge-balanced current pulses into a colonised block, read sixteen electrodes, and let ridge regression do the only learning in the system. The fungus is the reservoir; it is not a brain.',
    category: 'mycelium',
    difficulty: 'master',
    buildTime: '6–9 weeks (3 of colonisation, 4–6 of bench work)',
    costBand: '$$$',
    wakandaIndex: 92,
    diyFeasibility: 40,
    scienceGrounding: 62,
    realitySplit: {
      real: 'Reservoir computing is a real, well-posed method: a fixed, high-dimensional, nonlinear dynamical system with fading memory, plus a linear readout trained by regression (Jaeger 2001 echo-state networks; Maass 2002 liquid-state machines; Tanaka et al. 2019 review). A colonised mycelium composite is genuinely such a system — it has nonlinear voltage responses, slow state variables (moisture, ion gradients) and measurable fading memory. A 2025 preprint reports an actual mycelium-chip reservoir on the NARMA-10 task at NRMSE ≈ 0.98, which is itself the honest headline: it works, and it is barely better than predicting the mean.',
      narrative: '"The fungus thinks." It does not. A reservoir is a bucket of dynamics; every weight that matters is computed on your laptop. No synaptic plasticity in the substrate is needed for this project, and none is demonstrated by it. There is no evidence of any computational advantage over a $2 microcontroller running the same regression on the same features, and the substrate drifts over days — your own drift log will show it.',
    },
    summary: 'A complete, honest reservoir-computing rig for a living substrate. Sixteen recessed gold electrodes read a colonised mycelium block while a separate drive pair injects biphasic current pulses; a 24-bit biopotential front end streams the response to disk. You then do the standard reservoir-computing work: verify the fading-memory property, build a temporal classification task, fit a ridge readout, and benchmark it against a sterile block, a linear model with no substrate, and shuffled labels. The deliverable is an accuracy table plus a 14-day drift curve.',
    science: 'Reservoir computing splits a temporal task into (1) a fixed dynamical system that nonlinearly expands input history into a high-dimensional state and (2) a linear readout trained by least squares. The formal requirements are the separation property, the fading-memory (echo-state) property, and enough effective dimensionality. Inject the input as charge-balanced biphasic current pulses (10 µA to 1 mA, 1–100 ms, 0.2–2 Hz). The substrate\'s distributed ionic RC network spreads that into a spatiotemporal voltage pattern sampled at 16 electrodes at 250–1000 Hz. Features are a sliding window of all channels (0.5 s × 1000 Hz × 16 = 8000 features) and ridge regression handles the ill-conditioning. Time constants here are seconds, so tasks must live at that timescale. Benchmark against four conditions: living block, autoclaved block at identical moisture, linear model on raw stimulus with no substrate, and the living pipeline with shuffled labels. If the sterile block matches the living block, you measured electrochemistry, not computation.',
    billOfMaterials: [
      { item: 'Trametes versicolor or Pleurotus ostreatus grain spawn (2 kg)', qty: '1 bag', note: 'Buy from a commercial supplier; never culture wild moulds' },
      { item: 'Pasteurised hemp hurd or hardwood sawdust, 4–8 mm', qty: '5 kg' },
      { item: '16-channel gold-plated (ENIG) electrode array PCB, 2 mm pitch, recessed', qty: '3', note: 'One per block; recess so electrodes sit flush with the surface' },
      { item: 'Ag/AgCl pellet reference electrode + 2 × 316 stainless drive pins', qty: '1 set', note: 'Keep the drive pair geometrically far from the sense array' },
      { item: 'ADS1299 8-channel 24-bit biopotential ADC breakout', qty: '2', note: 'Two boards for 16 channels; 250–1000 SPS, internal reference (~$70 each)' },
      { item: 'Howland current pump: OPA551 or LT1210 + 0.1% resistors, ±1 mA', qty: '1', note: 'Biphasic pulses only. Never DC into a wet ionic sample (~$15)' },
      { item: 'ESP32-S3 or Raspberry Pi Pico + microSD, 1 kHz sustained logging', qty: '1 set', note: '~$12' },
      { item: 'SHT45 temperature/RH logger + 0.1 g scale', qty: '1 set', note: 'Moisture is your dominant drift covariate; log it with every trial (~$10)' },
      { item: 'Die-cast aluminium enclosure + copper tape + 12 V SLA battery', qty: '1 set', note: 'Float the whole front end; no mains cable enters the box' },
      { item: 'Incubation monotub, filter patch, 25 °C thermostat', qty: '1 set', note: '~$15' },
    ],
    buildSteps: [
      { title: 'Colonise, then equilibrate before you measure anything', detail: 'Grow the block at 25 ± 2 °C until fully white (10–21 days), then move it into the recording enclosure and leave it 48 hours. Freshly moved blocks produce movement and moisture artefacts that swamp everything. Log mass and humidity from hour zero.' },
      { title: 'Build the 16-channel front end on a ground plane', detail: 'Two ADS1299 boards, short guarded input traces, and a separate drive channel with its own return. Verify the noise floor with inputs shorted (<1 µV RMS, 0.5–100 Hz) before any biology. If you cannot hit that on the bench, fix the electronics first — the substrate imposes nothing but trouble on top of a bad front end.' },
      { title: 'Characterise the bare electrochemistry', detail: 'Measure electrode-pair impedance spectra for every combination, and record a full sterile-block dataset with the identical protocol. This null dataset is the entire scientific value of the project.' },
      { title: 'Verify the fading-memory property', detail: 'Apply one short pulse and fit the voltage decay. If the response does not decay back toward baseline, you have a saturated electrochemical cell, not a fading-memory reservoir, and no amount of regression will fix it.' },
      { title: 'Build a temporal stimulus set with a random schedule', detail: 'Four classes: single pulse at three amplitudes; paired pulses at three inter-pulse gaps; three spatial patterns of drive electrode pair. 200 trials per class, randomised, 10 s rest between trials so the reservoir returns to baseline. Log ground truth to the same CSV as the voltages.' },
      { title: 'Extract features and fit a ridge readout', detail: 'Mean-subtract each channel to remove electrode drift, window at 0.5 s with 0.1 s stride, standardise, and fit RidgeClassifier. Tune α by cross-validation grouped by recording day. Split by day, never by trial — trials minutes apart share one drifting state and a random split reports an accuracy you can never reproduce.' },
      { title: 'Run every control in the same session', detail: 'Sterile block, no-substrate linear model, shuffled labels, living block. Same features, same folds, same α search. Report all four numbers side by side, with the chance level stated explicitly.' },
      { title: 'Log drift for 14 days at fixed moisture', detail: 'Repeat a fixed 50-trial test every day and plot accuracy against days since inoculation. That curve is the honest result of the project, and it is the number any future bio-hybrid computer has to beat.' },
    ],
    code: {
      language: 'python',
      snippet: [
        '"""Ridge readout for a mycelial reservoir. Features: windowed 16-channel voltage."""',
        'import numpy as np',
        'from sklearn.linear_model import RidgeClassifier',
        'from sklearn.model_selection import GroupKFold',
        'from sklearn.pipeline import make_pipeline',
        'from sklearn.preprocessing import StandardScaler',
        '',
        'def window(v, win=500, stride=100):',
        '    """v: (n_samples, 16) volts. Returns (n_windows, 16*win), mean removed per channel."""',
        '    v = v - v.mean(axis=0, keepdims=True)          # kill electrode drift first',
        '    return np.stack([v[i:i + win].ravel() for i in range(0, len(v) - win, stride)])',
        '',
        'X, y, day = load_trials()      # your logger: features, class label, recording day',
        'splits = GroupKFold(n_splits=5).split(X, y, day)',
        'for tr, te in splits:',
        '    clf = make_pipeline(StandardScaler(), RidgeClassifier(alpha=1.0))',
        '    clf.fit(X[tr], y[tr])',
        '    chance = max(np.bincount(y[te])) / len(te)',
        '    print(f"acc={clf.score(X[te], y[te]):.3f}  chance={chance:.3f}")',
      ].join('\n'),
      note:
        'Split by recording day, never by trial. Then repeat the whole script on the sterile-block CSV. If the two accuracies are within noise of each other, the honest result is that the living substrate added nothing.',
    },
    metrics: [
      { label: '4-class temporal accuracy vs controls', value: 'report living vs sterile vs linear vs shuffled, all on the same folds (measured)' },
      { label: 'NARMA-10 NRMSE', value: 'published mycelium chip ≈0.98; predicting the mean scores 1.0 (measured — compare your own)' },
      { label: 'fading-memory time constant', value: 'seconds to tens of seconds, from a single-pulse decay fit (measured)' },
      { label: 'linear memory capacity', value: 'sum of squared correlations over delays; expect low single digits for a slow ionic substrate (measured)' },
      { label: 'accuracy retention at day 14', value: '% of day-1 accuracy at fixed moisture (measured)' },
      { label: 'input-referred noise, electrodes in the live block', value: '<2 µV RMS, 0.5–100 Hz (measured)' },
    ],
    stretchGoals: [
      'Compute the participation ratio of the state covariance and test whether dimensionality predicts task accuracy across blocks.',
      'Swap the readout for a plain linear SVM and see whether the choice of readout even matters at this noise level.',
      'Run two blocks of different species in parallel and test whether their errors are correlated.',
      'Publish the negative result if the sterile block matches the living block — that result is worth more than a marginal win.',
    ],
    safety: [
      'Buy spawn from a commercial supplier and never culture wild moulds. You will keep a colonised block at high humidity on a bench for weeks, and toxigenic Aspergillus or Trichoderma look like white mycelium to an untrained eye. If in doubt, seal it and discard it.',
      'Wear an N95/P2 respirator, nitrile gloves and eye protection for every step that disturbs dry spawn, dry substrate or the block. Handle the block in a still-air box or under HEPA extraction, never in a bedroom or a kitchen.',
      'Anyone immunocompromised, pregnant, asthmatic or with a transplant history must not be in the workspace. Invasive aspergillosis from ordinary mould exposure is a documented risk for those groups and no home HEPA setup removes it.',
      'Drive the block only from a battery-powered, current-limited stimulator (≤1 mA and a 100 kΩ series resistor in every drive line). Never let a mains-referenced supply touch the wet block: a damp ionic substrate is a resistive path to whatever you touch. Never combine wet organic substrate with mains voltage.',
      'Keep the enclosure, the block and the battery in one grounded metal box with no mains cable entering it. Autoclave or 10% bleach-soak the spent block for 30 minutes and dispose of it sealed; do not compost experimental substrate.',
    ],
    lessonLinks: ['w6l11', 'w6l12', 'w5l10'],
    sources: [
      { label: 'bioRxiv 2025 — morphologically tunable mycelium chips for physical reservoir computing (NARMA-10 NRMSE ≈ 0.98)', url: 'https://www.biorxiv.org/content/10.1101/2025.08.20.671348v1' },
      { label: 'Tanaka et al., Neural Networks 115 (2019) — recent advances in physical reservoir computing: a review', url: 'https://dl.acm.org/doi/10.1016/j.neunet.2019.03.005' },
      { label: 'Utrecht University — electronic properties of fungi and sensorial/computing circuits in mycelium', url: 'https://dspace.library.uu.nl/bitstream/handle/1874/416274/1_s2.0_S0303264721002288_main.pdf' },
      { label: 'Advanced Intelligent Systems — mycelium-inspired memristive reservoir computing (silicon inspired by mycelium, not living fungus)', url: 'https://advanced.onlinelibrary.wiley.com/doi/10.1002/aisy.202501384' },
    ],
  },

  {
    id: 'myc-advanced-hybrid-skin',
    title: 'Awọ-Àdapọ̀ — Myco-Silicon Hybrid Tactile Skin',
    tagline: 'A living composite over-layer for slow adaptation and load history, a piezoresistive array underneath for millisecond contact. Measure both paths, then show what the hybrid knows that neither half does.',
    category: 'mycelium',
    difficulty: 'journeyman',
    buildTime: '5–7 weeks',
    costBand: '$$$',
    wakandaIndex: 84,
    diyFeasibility: 62,
    scienceGrounding: 70,
    realitySplit: {
      real: 'Two timescales are separately measurable. A piezoresistive or capacitive array detects contact in single-digit milliseconds with millimetre-scale spatial resolution — standard e-skin engineering. A mycelium composite layer genuinely changes impedance and stiffness with moisture, compression and time under load, and published work shows living mycelium composites discriminating weights from patterns of electrical activity. The hybrid gives a fast event channel and a slow history channel, and you can quantify exactly what the slow channel adds with a classification task.',
      narrative: '"Skin that feels and remembers like flesh." The mycelium has no mechanoreceptors. It is a hysteretic, humidity-dominated ionic resistor and a viscoelastic pad. Adaptation, memory and touch are names we give to impedance drift and creep in a wet organic composite. The honest project measures that drift, then decides whether it is useful.',
    },
    summary: 'A 40 × 40 mm patch: a 4 × 4 piezoresistive array scanned through a 16-channel multiplexer, covered by a 3 mm living mycelium composite pad with four coplanar electrodes on its underside. Characterise the fast path (latency, spatial resolution, cross-talk) and the slow path (time constant, creep, hysteresis, recovery), then run the task the hybrid should win: detect contact onset from the fast channel and discriminate a 0.5 s tap from a 3 s press from a 10 s sustained load using only the slow channel.',
    science: 'The fast path is classical: a force-sensitive resistive sheet changes resistance under pressure, and scanning 16 cells at 1 kHz through a 74HC4067-class multiplexer into a 16-bit ADC gives contact latency of a few milliseconds, limited by scan rate, ADC settling and elastomer relaxation. The slow path is electrolytic. Because conduction is ionic, the impedance depends on moisture, ionic strength and compression, so it must be measured with a 1 kHz, 100 µA AC excitation and synchronous demodulation — DC polarises the electrodes and electrolyses the mat within minutes. The control that makes the project honest is to press the pad inside a saturated-humidity chamber where evaporation cannot change: whatever response remains is the mechanotransduction signal. Expect it to be far smaller than the humidity response, and expect 10–60 minutes of recovery after a 200 g press. The hybrid claim stands or falls on whether the slow channel predicts hold duration better than the fast channel alone.',
    billOfMaterials: [
      { item: 'Living mycelium composite pads, 40 × 40 × 3 mm on hemp hurd', qty: '4', note: 'Trametes or Pleurotus; harvest at 10–14 days, reject thickness outside ±15%' },
      { item: 'Velostat / Linqstat piezoresistive sheet (or a commercial FSR matrix)', qty: '1 sheet', note: '~$12' },
      { item: '74HC4067 16-channel analog multiplexer + ADS1115 16-bit ADC', qty: '1 set', note: 'Scan rate sets your fast-path latency; measure it, do not assume it (~$4)' },
      { item: 'AD5933 impedance analyser breakout (or ADG419/AD630 synchronous demodulator)', qty: '1', note: 'Real and imaginary parts of the pad impedance (~$25)' },
      { item: 'INA333 instrumentation amplifier + REF5025 reference', qty: '1 set', note: '~$18' },
      { item: 'ESP32-S3 + microSD logger', qty: '1 set', note: '~$12' },
      { item: 'Sensirion SHT45 temperature/RH reference', qty: '1', note: 'Ground truth for the humidity confound (~$10)' },
      { item: 'Saturated salt RH standards: MgCl₂ 33%, NaCl 75%, K₂SO₄ 97% + desiccator', qty: '1 set' },
      { item: 'Calibrated weight set 10/50/200/500 g + 5 kg load cell + HX711', qty: '1 set', note: 'Defined contact pressure is not optional (~$25)' },
      { item: 'Silicone conformal coating (e.g. MG 422B) + 3M 5952 tape', qty: '1 set', note: 'Every board near the pad gets coated' },
    ],
    buildSteps: [
      { title: 'Grow flat, consistent pads and measure them like specimens', detail: 'Spread colonised substrate 3 mm deep in a flat tray and knit for 10–14 days at 25 °C. Press lightly to uniform thickness, dry to stable mass, and record thickness to 0.1 mm and density for every pad. Thickness and density drive both the mechanics and the impedance, so unequal pads make the whole comparison meaningless.' },
      { title: 'Fabricate and calibrate the fast array', detail: 'Laminate the piezoresistive sheet into a 4 × 4 grid with copper tape traces, or buy an FSR matrix and characterise it. Measure per-cell force versus resistance with the weight stack, in the divider circuit you will actually use. Sensitivity is strongly non-linear and cell-to-cell variance is large; fit each cell, do not use one global curve.' },
      { title: 'Measure the true fast-path latency', detail: 'Drop a known mass on one cell and log the ADC stream at maximum rate. Latency is the delay from impact (use an accelerometer as the time reference) to threshold crossing. Then measure scan-rate-limited latency for all 16 cells. Report both numbers in milliseconds.' },
      { title: 'Laminate the living layer at a defined contact pressure', detail: 'Bond the pad to the array under a fixed recorded mass — 200 g over 30 × 30 mm is about 2.2 kPa. Not doing this is the single most common reason these experiments fail, because contact resistance then varies more than the signal.' },
      { title: 'Separate touch from moisture with the saturated-humidity control', detail: 'Apply 10, 50 and 200 g loads twice: once in room air, once inside a saturated-humidity chamber where evaporation is suppressed. The difference between the two curves is the honest mechanotransduction signal. If it is under 0.5% of |Z|, write that down.' },
      { title: 'Characterise creep, hysteresis and recovery', detail: 'Hold 200 g for 10 minutes and log |Z| throughout: the drift is creep. Step up and back down to measure hysteresis. Then remove the load and log recovery — expect 10–60 minutes. These three curves are the slow channel\'s specification.' },
      { title: 'Run the hybrid classification task', detail: 'Twenty trials each of tap (0.5 s), press (3 s) and sustained load (10 s), in random order. Classify with the fast channel alone, the slow channel alone, and both. Report accuracy and per-class confusion. Then fit a simple estimator of cumulative impulse from the slow channel and report its error in N·s.' },
      { title: 'Mount it on a moving robot and re-measure', detail: 'Wrap the patch on a bumper and drive into a wall at 0.1, 0.3 and 0.5 m/s. Report the maximum speed at which the hybrid stops within 5 cm. Vibration and airflow are the real confounders, and they only appear once the sensor moves.' },
    ],
    metrics: [
      { label: 'fast-path contact latency', value: 'target <10 ms including scan time, verified against an accelerometer (measured)' },
      { label: 'slow-path step time constant', value: 'seconds to tens of seconds (measured)' },
      { label: 'mechanotransduction signal above the humidity artefact', value: 'Δ|Z|/|Z| in the saturated-humidity control; report it even at 0.2% (measured)' },
      { label: 'recovery time after a 200 g press', value: 'expect 10–60 minutes (measured)' },
      { label: 'hybrid 3-class accuracy (tap/press/hold)', value: 'fast-only vs slow-only vs hybrid, on the same folds (measured)' },
      { label: 'baseline drift over 24 h', value: 'report %/hour at fixed humidity (measured)' },
    ],
    stretchGoals: [
      'Add a Kelvin (four-electrode) measurement on the pad and show how much of the slow signal was electrode polarisation.',
      'Sweep 1 Hz–100 kHz and fit a Randles equivalent circuit to the pad; report the fitted double-layer capacitance.',
      'Train the slow channel to estimate total impulse and use it to trigger a gentle-release behaviour on a gripper.',
      'Repeat with a dead (autoclaved) pad to show how much of the slow channel is biology and how much is just wet hemp.',
    ],
    safety: [
      'Buy spawn from a commercial supplier; never culture wild moulds. A high-humidity pad on a bench is also the ideal habitat for contaminants, and you will be handling it repeatedly.',
      'Wear an N95/P2 respirator, gloves and eye protection whenever you cut, sand or handle a dry pad. Dry mycelium composite sheds spore-laden dust, and the highest dose occurs exactly when you trim a specimen.',
      'Exclude immunocompromised people from the workspace entirely. Weeks of repeated handling of sporulating material is a materially higher Aspergillus exposure than a one-off mycology project.',
      'Power the whole patch from an isolated ≤12 V current-limited supply with a 1 MΩ series resistor in every electrode line. A wet ionic pad is a resistive path, and a mains-referenced supply anywhere on the bench creates a shock path across it. Never combine wet organic substrate with mains voltage.',
      'Conformal-coat every board that lives near the pad and run it from a battery or an isolated DC/DC converter, so a condensation event cannot bridge to anything earth-referenced.',
    ],
    lessonLinks: ['w2l4', 'w5l10', 'w6l11'],
    sources: [
      { label: 'Journal of Bioresources and Bioproducts — living mycelium composites discern weights via patterns of electrical activity', url: 'http://jbb.xml-journal.net/en/article/doi/10.1016/j.jobab.2021.09.003?viewType=HTML' },
      { label: 'arXiv:2210.01839 — reactive fungal insoles (mycelium as a wearable sensing material)', url: 'https://arxiv.org/abs/2210.01839' },
      { label: 'Flexible tactile sensor array review — spatial resolution and scan-rate limits of robot skin', url: 'https://core.ac.uk/download/491504421.pdf' },
      { label: 'Advanced Engineering Materials — biosensing abilities of living mycelium materials', url: 'https://advanced.onlinelibrary.wiley.com/doi/pdf/10.1002/adem.202501759' },
    ],
  },

  {
    id: 'myc-advanced-tensegrity',
    title: 'Ilé-Ìdúró — Mycelium Tensegrity Field Habitat Module',
    tagline: 'Grow the compression struts, tension a cable net around them, and compare the assembled module against the same geometry in 6061 aluminium. Specific stiffness is where you lose; shipped mass and damping are where you win.',
    category: 'mycelium',
    difficulty: 'master',
    buildTime: '8–12 weeks (4–6 of it colonisation and drying)',
    costBand: '$$$',
    wakandaIndex: 88,
    diyFeasibility: 45,
    scienceGrounding: 66,
    realitySplit: {
      real: 'Tensegrity is well-understood structural engineering: a discontinuous set of compression members inside a continuous tension net, whose stiffness comes from prestress rather than bending. Mycelium composites are a real, measured structural material — compressive strength roughly 0.1–1.2 MPa and flexural modulus tens to a few hundred MPa depending on substrate and pressing — and self-organised mycelium biocomposites show geometry-dependent compressive behaviour. Strut modulus, module stiffness, mass and deployment time are all measurable on a scale, a dial indicator and a load cell.',
      narrative: '"A grown habitat." The biology supplies compression members for a 2 m demonstrator, not a Mars house. The airtight, load-rated, radiation-shielding envelope of a real habitat is a separate and much harder problem. The honest, buildable artefact here is the frame and its measured stiffness-to-mass ledger.',
    },
    summary: 'A 2 m tensegrity module: six to twelve grown mycelium composite struts in compression, pre-tensioned by a cable net of steel or Dyneema, assembled with printed or cast socket caps. You characterise single struts in compression, then the assembled module, then the same geometry in 6061-T6 tubes sized for equal failure load. The output is a fair comparison table — equal-load, not equal-wall-thickness — plus deployment time and a clear statement of which members mycelium should and should not be trusted with.',
    science: 'Tensegrity carries load only when the net is pretensioned; struts then see almost pure axial compression and cables see pure tension. That division of labour suits a material with usable compression and poor bending, which is exactly what a mycelium composite is. Grow struts in HDPE pipe moulds (600–1200 mm long, 40–60 mm bore), dry to constant mass, and cap the ends with sockets that put every cable attachment on the strut axis so no bending moment is introduced. Design the prestress so no strut ever goes into tension. Measure: (1) single-strut compressive modulus and failure load in a rig, three specimens per batch; (2) assembled module stiffness by hanging a known mass at the centre and reading deflection with a dial indicator; (3) total mass and deployment time. Then compare against 6061-T6 tubes selected to fail at the same load. Expect specific stiffness (E/ρ) roughly 30–150× below aluminium, because E is 20–150 MPa against 69 GPa while density is only ~10–17× lower. That loss is real; the gains are a shipped mass of a few kilograms of spawn and substrate instead of tens of kilograms of metal, and internal damping several times higher than aluminium.',
    billOfMaterials: [
      { item: 'Pleurotus ostreatus or Trametes versicolor sawdust spawn (5 kg)', qty: '1 bag', note: 'Commercial supplier only' },
      { item: 'Hemp hurd or straw, 3–8 mm, pasteurised at 75 °C for 60 min', qty: '25 kg' },
      { item: 'HDPE pipe moulds, 1.2 m × 50 mm bore, split lengthwise + hose clamps', qty: '12', note: 'Split moulds for demoulding; clamp to control diameter' },
      { item: 'Tension net: 3 mm Dyneema or 2 mm 316 stainless wire rope + ferrules', qty: '60 m', note: 'Dyneema has less creep and is safer if it fails (~$80)' },
      { item: 'M8 stainless turnbuckles + load-rated ratchet straps for prestress', qty: '12', note: 'Turnbuckles let you set and log prestress repeatably (~$8 each)' },
      { item: '5 kN load cell + HX711/ADS1232 + Arduino for strut and net tension', qty: '1 set', note: '~$25' },
      { item: 'Dial indicator (0.01 mm) + magnetic base + 20 kg test masses', qty: '1 set', note: 'Module stiffness measurement' },
      { item: 'Moisture meter + 0.5 g scale + 1 m steel rule', qty: '1 set', note: 'Dry mass and shrinkage control' },
      { item: '6061-T6 tube, 50 mm OD × 3 mm wall, 1.2 m (control set)', qty: '6', note: 'The honest comparison column (~$15/m)' },
      { item: 'Greenhouse film, shade cloth and a 25 °C incubation tent', qty: '1 set', note: 'Colonisation and long slow drying without rain' },
    ],
    buildSteps: [
      { title: 'Fix the geometry and the prestress before you grow anything', detail: 'Choose a standard tensegrity topology (a 3-bar prism is the cheapest useful demonstrator) and compute the strut axial force under design prestress plus design load. Every strut must stay in compression with a margin. Write the numbers down; a mycelium strut that goes into tension has no reliable strength data behind it.' },
      { title: 'Grow struts with process control, not hope', detail: 'Pack the split moulds to a consistent bulk density (record it), incubate at 25 ± 2 °C in the dark, and demould at 7–10 days. Dry at 60–70 °C for 24–48 h to constant mass. Log the mass every few hours — the drying curve is your process control, and wet struts are both weak and dimensionally unstable.' },
      { title: 'Seal and cap the struts', detail: 'Sand to a consistent diameter, seal with two coats of shellac or linseed oil, and bond printed sockets with epoxy so the cable attachment points sit exactly on the strut axis. Water uptake can approach 200% by mass in some formulations and will destroy both stiffness and fit.' },
      { title: 'Measure every strut in compression', detail: 'Compress each strut axially at 1 mm/s between platens with a spherical seat, logging force and displacement to 30% strain or failure. Compute secant modulus and report mean ± spread across three specimens per batch. Never report a single mycelium specimen as a material property.' },
      { title: 'Assemble and set the prestress', detail: 'Build the module on a flat floor, tension the net with turnbuckles to the design prestress measured by an in-line load cell, and record the turnbuckle position for every cable so the structure is exactly repeatable. Photograph and log the assembly sequence and the elapsed time.' },
      { title: 'Measure module stiffness and damping', detail: 'Hang 5, 10 and 20 kg at the module centre, read deflection with the dial indicator, and fit N/mm. Then displace the top node and release, logging the decay with an accelerometer to get the damping ratio by log decrement. Compare against the aluminium module of equal failure load.' },
      { title: 'Build the honest comparison table', detail: 'Rows: strut modulus, module stiffness, total mass, shipped mass (spawn + substrate + cable vs metal), deployment time, damping ratio, specific stiffness. Add one line stating where mycelium is the wrong material. That line is the most valuable output of the build.' },
      { title: 'Field-test for one wet season', detail: 'Leave the module outdoors with a humidity and temperature logger for 8 weeks. Re-measure stiffness and mass. Moisture ingress is the failure mode that decides whether any of this is deployable, and you can only find it with time.' },
    ],
    metrics: [
      { label: 'strut compressive strength', value: '0.1–1.2 MPa (measured; report mean ± spread over 3 specimens)' },
      { label: 'strut secant modulus', value: '20–150 MPa (measured) vs ~69,000 MPa for 6061-T6' },
      { label: 'module stiffness', value: 'N/mm at the centre node, prestressed (measured)' },
      { label: 'specific stiffness ratio vs 6061-T6', value: 'expect 30–150× lower (measured — state it plainly)' },
      { label: 'total deployed mass and shipped mass', value: 'kg on a 0.5 g scale; report both figures (measured)' },
      { label: 'stiffness retention after 8 weeks outdoors', value: '% of day-0 stiffness (measured)' },
    ],
    stretchGoals: [
      'Grow a node as a single piece by bio-welding three socket caps into one component and delete the bolted joint.',
      'Fill the strut cores with a sand or regolith analogue after growth and re-measure stiffness and mass.',
      'Compare Dyneema and stainless nets for creep over 8 weeks under constant prestress.',
      'Scale to a 4 m module and measure how the stiffness-to-mass ratio degrades with size.',
    ],
    safety: [
      'Buy spawn from a commercial supplier; never culture wild moulds, and discard any colonisation bag showing green, black or pink contamination. Sealed, labelled disposal — not the compost heap.',
      'Wear an N95/P2 respirator, gloves and eye protection for packing dry substrate, demoulding and every sanding or cutting step. Dry composite dust carries spores, and mould-filling is the peak dust event.',
      'A tensioned cable net stores real energy. Never stand or reach in the plane of a tensioned cable, wear safety glasses, use rated hardware with the correct ferrules, and apply prestress progressively while watching a load cell. A 3 mm Dyneema cable under kilonewtons can cut through skin if it fails.',
      'Anyone immunocompromised must stay out of the workspace; you are running a weeks-long humid incubation at multi-kilogram scale.',
      'Keep the incubation tent and its heater on a ground-fault-protected circuit with a thermostat and a hard thermal cut-out at 32 °C. Never run mains-powered heating or sensing into the wet tent; use an isolated low-voltage supply with conformal coating. Never combine wet organic substrate with mains voltage.',
    ],
    lessonLinks: ['w1l2', 'w8l15', 'w5l9'],
    sources: [
      { label: 'Journal of the Mechanical Behavior of Biomedical Materials — self-organized mycelium biocomposites: geometry and laterite effects on compressive behaviour', url: 'https://pubmed.ncbi.nlm.nih.gov/37075528/' },
      { label: 'Nature Communications 2025 — 3D printed gyroid scaffolds for strong, thermally insulating mycelium-bound composites', url: 'https://www.nature.com/articles/s41467-025-61369-x' },
      { label: 'Journal of Materials Science — review: mechanics of mycelium materials', url: 'https://link.springer.com/content/pdf/10.1007/s10853-026-13104-0.pdf' },
      { label: 'SUPERball v2 — a deformable tensegrity rover for planetary exploration (deployment and stiffness context)', url: 'https://helge-wurdemann.com/wp-content/uploads/2018/08/poster_iros2018workshop_tensegrity.pdf' },
      { label: 'ESA ARI study — growing fungi structures in space', url: 'https://www.esa.int/gsp/ACT/doc/ARI/ARI%20Call%20doc/Study%20descriptions/ARI-study_16-6101.pdf' },
    ],
  },

  {
    id: 'myc-advanced-self-replicating',
    title: 'Ẹ̀rọ-Àbímọ́ — Self-Replicating Mycelium Construction Swarm',
    tagline: 'A rover that inoculates local waste and grows its own replacement structural parts. Then the ledger: grams grown per day against grams built per day, and the honest verdict that biology loses by two to three orders of magnitude.',
    category: 'mycelium',
    difficulty: 'orisha',
    buildTime: '10–14 weeks',
    costBand: '$$$$',
    wakandaIndex: 95,
    diyFeasibility: 20,
    scienceGrounding: 32,
    realitySplit: {
      real: 'Every subsystem is real and measurable: a rover that maps substrate, doses spawn slurry at a controlled rate, and returns to harvest grown parts; a growth-versus-build ledger in grams per day and grams per watt-hour; and a working demonstration that a robot can grow a passive bracket and later bolt it to itself. The measurement plan — radial growth rate, part mass versus time, robot build rate, break-even inequality — is straightforward engineering.',
      narrative: 'Exponential self-replication. Von Neumann kinematic self-reproduction is a mathematical existence result, not an engineering plan, and biology is far too slow here. A mycelium part needs 10–28 days to colonise; an equivalent PLA part prints in under an hour. With a 30% growable mass fraction on a 10 kg robot, one robot grows 3 kg in about three weeks — a best-case doubling time near three weeks, about 17 doublings a year, with perfect logistics, zero contamination and no failures. Calling that a self-replicating swarm is storytelling. Calling it in-situ passive-part manufacturing is accurate.',
    },
    summary: 'A ground rover with a hopper, a peristaltic dosing pump and an injector tine array that lays spawn slurry into crop residue or waste substrate. It geotags and re-visits growth plots, weighs grown parts on a load cell, and prints its own non-growable brackets. The core deliverable is not the robot — it is the ledger: a measured growth rate in g/day and a measured build rate in g/h, a growth-to-build ratio, and a written break-even analysis showing precisely which parts biology can and cannot supply.',
    science: 'Mycelium radial growth through lignocellulosic substrate is typically on the order of 1–10 mm/day depending on species, substrate and temperature, and full colonisation of a moulded part takes 10–28 days, with demould windows of 7–10 days reported for Pleurotus and Trametes. A grown bracket is therefore a three-week-lead-time manufactured part. Measure its mass accumulation directly: weigh the mould every 48 h and subtract the dry substrate baseline, giving g/day. Contrast with an FDM printer at roughly 20 g/h, or a small CNC cutting aluminium at 10–100 g/min. The break-even is explicit. Let f be the growable mass fraction of a robot of mass m, ġ the growth rate and ḃ the build rate. Self-replication pays only when m·f/ġ < m(1−f)/ḃ. With realistic numbers — f = 0.3, ġ = 2 g/day, ḃ = 20 g/h = 480 g/day — the left side is 1500 days and the right is 14.6 days: biology is about 100× too slow for the robot itself, and closer to 1000× if you count the energy and area of the grow house. The correct engineering conclusion is layering, not replacement: use biology for large, low-precision, low-load, high-volume parts made from local waste where transport mass dominates, and metal and polymer for everything on the critical path. Publish the failure as the result.',
    billOfMaterials: [
      { item: '4WD chassis, 100 mm wheels, 4 × 12 V 30 rpm gearmotors with encoders', qty: '1', note: 'Ground clearance for a residue windrow' },
      { item: 'BTS7960 or Cytron MDD10A drivers + ESP32-S3 + GPS (u-blox NEO-M9N)', qty: '2 + 1', note: 'Geotag every dosing and weighing waypoint (~$12)' },
      { item: 'Peristaltic dosing pump, 12 V, 30–100 mL/min', qty: '1', note: 'Spawn slurry is abrasive; peristaltic does not clog (~$35)' },
      { item: '20 L hopper + slow 12 V agitator + spring-steel injector tines at 100 mm spacing', qty: '1 set', note: 'Guard the tines; they are the main pinch hazard' },
      { item: '5 kg load cell + HX711 for part mass accumulation logging', qty: '1 set', note: 'Weigh the mould in place every 48 h (~$25)' },
      { item: 'SHT45 + CO₂ sensor in a small sampling hood for the growth plots', qty: '1 set', note: '~$10' },
      { item: 'FDM printer with a 250 mm bed for the non-growable brackets', qty: '1', note: 'The control column in the build-rate ledger' },
      { item: 'Pleurotus ostreatus or Trametes versicolor spawn, 20 kg, + pasteurised hemp hurd or straw', qty: '1 set' },
      { item: 'Reusable HDPE part moulds, 6 geometries, with demould release', qty: '24', note: 'Three replicates per geometry for real error bars' },
      { item: 'Watt meter on the printer and the grow-house heater', qty: '2', note: 'Report g per Wh for both paths — this is the number that kills the myth' },
    ],
    buildSteps: [
      { title: 'Define the parts the robot will grow, and their load cases', detail: 'Pick four to six genuinely non-critical parts: battery tray, sensor mast base, bumper, cable guide. Write the load for each. Reject anything structural or safety-related — this is where the honesty of the whole project is established.' },
      { title: 'Build the dosing pass and calibrate it', detail: 'Lay a residue windrow 300 mm high, mix spawn slurry at 15–25% wet mass, and dose at 200 mL/m through the peristaltic pump into the top 50 mm. Calibrate the pump gravimetrically over 10 m and log the dose per metre, geotagged.' },
      { title: 'Grow parts and weigh them every 48 hours', detail: 'Fill the reusable moulds to a recorded bulk density, incubate at 25 ± 2 °C, and weigh each mould on the load cell every 48 h to build a mass-versus-time curve. Subtract the dry substrate baseline and fit g/day. Three replicates per geometry, or your rate is noise.' },
      { title: 'Measure the robot build rate honestly', detail: 'Print the identical part geometries in PLA and log the watt meter and print time, giving g/h and g/Wh. Machine one in aluminium if you have access, and log spindle time. The comparison must include the grow house area, heating energy and three weeks of occupancy.' },
      { title: 'Assemble a grown part onto the robot', detail: 'Harvest, dry, seal and bolt one grown bracket to the rover, then run the rover for a week with that bracket in service. This is the demonstration that matters: a robot structurally using a part it grew on site.' },
      { title: 'Write the break-even inequality with your own numbers', detail: 'Plug your measured ġ, ḃ, f and m into m·f/ġ < m(1−f)/ḃ and report the ratio. Then state the part classes where the inequality flips — insulation, filler, non-structural panels, soil stabilisation — and the classes where it never will.' },
      { title: 'Run a contamination and failure audit', detail: 'Count how many of your moulds were lost to contamination, under-colonisation or breakage. A replication process with a 30% loss rate has an effective growth rate 30% lower, and this number is usually omitted from self-replication claims.' },
      { title: 'Publish the ledger and the limits', detail: 'Report g/day grown, g/h built, g/Wh for both, losses, and the break-even ratio. Include a plain statement that no exponential reproduction occurred and why the arithmetic forbids it at biological growth rates.' },
    ],
    metrics: [
      { label: 'radial colonisation rate', value: '1–10 mm/day depending on species and temperature (measured)' },
      { label: 'part mass accumulation rate', value: 'g/day, from 48-hour weighing of 3 replicates per geometry (measured)' },
      { label: 'robot build rate', value: 'g/h and g/Wh for the identical geometry in PLA (measured)' },
      { label: 'growth-to-build rate ratio', value: 'report the measured ratio and the break-even value (measured, computed)' },
      { label: 'mould loss rate', value: '% lost to contamination, under-colonisation or breakage (measured)' },
      { label: 'grow-house energy per grown gram', value: 'Wh/g including heating and lighting (measured)' },
    ],
    stretchGoals: [
      'Close the loop: let the rover re-dose plots that fall behind their predicted colonisation curve.',
      'Grow a part that is itself a mould for the next part, and measure how many generations the geometry survives.',
      'Run the same ledger with a local agricultural waste stream (rice husk, maize stover, coffee chaff) and report yield per kg of waste.',
      'Compute the land area required for the swarm to reproduce itself in one year and compare it to the swarm footprint.',
    ],
    safety: [
      'Buy spawn from a commercial supplier; never culture wild moulds. Outdoor inoculation is a dispersal event — check local rules before releasing any fungus, and use only a species already present in your region.',
      'Wear an N95/P2 respirator, gloves and eye protection when loading the hopper, running the agitator, and harvesting dried parts. Dry spawn and mouldy substrate dust is the main inhalation hazard and it peaks while you are loading a machine.',
      'The rover is a 20 kg machine with an exposed tine array and a rotating agitator. Fit a latching emergency stop within reach, guard the tines and the auger, and never service it with the battery connected. Spring-steel tines under load can flick and cut.',
      'Exclude immunocompromised people from the workspace. A multi-kilogram, weeks-long humid incubation is a high-exposure environment.',
      'Fuse the traction pack at the battery, charge LiPos in a fireproof bag on a non-flammable surface and never unattended, and keep all electronics in an IP65 enclosure with conformal coating. Never combine wet organic substrate handling with mains voltage, and never charge the pack on damp ground.',
    ],
    lessonLinks: ['w6l12', 'w8l16', 'w7l13'],
    sources: [
      { label: 'Ellery et al., i-SAIRAS — Manna from Heaven: preliminary efforts for a self-replicating 3D printer for lunar in-situ resource utilisation', url: 'https://www.semanticscholar.org/paper/Manna-from-Heaven-%E2%80%93-Preliminary-Efforts-for-a-3D-Ellery/97de5c2c0bf4d51ad2e13992888953af9bb59c08' },
      { label: 'Freitas & Merkle — Kinematic Self-Replicating Machines (the canonical account of what replication actually requires)', url: 'https://archive.org/details/kinematic-self-replicating/' },
      { label: 'International Journal of Astrobiology (Cambridge) — self-replicating machines: review and constraints', url: 'https://www.cambridge.org/core/services/aop-cambridge-core/content/view/S1473550422000234' },
      { label: 'Motamedi thesis (ÉTS Montréal) — colonisation and demould windows for Pleurotus and Trametes', url: 'https://espace.etsmtl.ca/id/eprint/3847/1/MOTAMEDI_Seyedsina_Th%C3%A8se.pdf' },
      { label: 'ETH Zürich — robot self-construction: systems and control problems', url: 'https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/149683/eth-29290-02.pdf' },
    ],
  },

  {
    id: 'myc-advanced-rad-shield',
    title: 'Ìdáàbò-Òkùnkùn — Melanised Mycelium Radiation and Thermal Shield',
    tagline: 'Melanin really does attenuate ionising radiation, and mycelium composites really are good insulators. Build a test panel, measure both in areal-density terms, and state plainly what is still unproven.',
    category: 'mycelium',
    difficulty: 'master',
    buildTime: '6–10 weeks',
    costBand: '$$$',
    wakandaIndex: 86,
    diyFeasibility: 30,
    scienceGrounding: 52,
    realitySplit: {
      real: 'Two measured facts. Melanised fungal material attenuates ionising radiation: radiotrophic Cladosporium sphaerospermum grown aboard the ISS attenuated the local dose measurably over 30 days, and melanin from Cryptococcus neoformans protects cells from lethal gamma doses. Mycelium composites are also genuine thermal insulators, with measured thermal conductivity around 0.04–0.06 W/(m·K), comparable to conventional insulation. Panel fabrication, density, thermal conductivity and flexural strength are all measurable at home; the radiation number needs a legal exempt source or a partner lab.',
      narrative: 'A melanin force field against cosmic rays. Attenuation is not a biological property — it is areal density and effective atomic number. A thin melanised layer buys a percent or two. Real Galactic Cosmic Ray dose reduction needs tens of grams per square centimetre of low-Z material, which is hundreds of kilograms per square metre: a regolith-filled wall, not a film. The best a fungus does there is bind the regolith and grow the structure. Self-repair of a shield in vacuum and under UV is an open hypothesis, not a demonstrated capability.',
    },
    summary: 'A test-panel programme in two halves. Half one is solid and fully DIY: fabricate melanised mycelium composite panels at three densities, measure thermal conductivity against a calibrated reference, and measure flexural strength and vacuum-cycling mass loss. Half two is the radiation measurement: attenuate a legal exempt-quantity gamma check source, or a partner-lab beamline, using matched-areal-density aluminium and water references, and report transmission ratios with honest counting statistics. The write-up must contain a section titled "what is not proven".',
    science: 'Photon attenuation follows I = I₀·exp(−(μ/ρ)·ρx), where μ/ρ is the mass attenuation coefficient and ρx the areal density. Above a few hundred keV, Compton scattering dominates and attenuation scales with electron density, so any low-Z organic composite behaves approximately like water: μ/ρ ≈ 0.07 cm²/g at 1 MeV, giving a half-value layer near 10 cm of water, about 100 kg/m². Melanin is a broadband absorber and radical scavenger and clearly protects at the cellular level, but it does not change that photon physics. Where melanised composites might genuinely help is neutron and charged-particle moderation, because hydrogen content matters — a real, testable hypothesis that remains largely unmeasured for mycelium composites. Measure three things properly: thermal conductivity with a heat-flux sensor or guarded hot plate against a known reference; density, thickness and areal density of every panel to 0.1 mm and 0.1 g; and gamma transmission against aluminium and water at matched areal density. A Geiger counter counting a weak source for ten minutes has large counting statistics and will not resolve a 2% difference — state your uncertainty or the measurement means nothing.',
    billOfMaterials: [
      { item: 'Melanin-producing inoculum: Aureobasidium pullulans, or Pleurotus melanised with tyrosine/Cu amendment', qty: '1 culture', note: 'Buy from a culture collection or a supplier; do not isolate from wild samples' },
      { item: 'Pasteurised hemp hurd or sawdust + panel moulds 200 × 200 × 30 mm', qty: '10 kg', note: 'Three densities: loose, packed, hot-pressed' },
      { item: 'Heat-flux sensor (e.g. FluxTeq PHFS-01) or guarded hot-plate rig + Peltier + PID driver', qty: '1 set', note: 'The primary thermal measurement (~$300)' },
      { item: 'Type-K thermocouples × 6 + MAX31855 amplifiers + ESP32 logger', qty: '1 set', note: 'Hot side, cold side, guard, ambient (~$12)' },
      { item: 'Calibrated reference insulation: 30 mm extruded polystyrene, known k', qty: '1', note: 'You must reproduce its k before you trust yours' },
      { item: 'Vacuum bagging kit + pump for hot-pressing and for vacuum-cycling tests', qty: '1 set' },
      { item: 'Legal exempt-quantity gamma check source (e.g. Cs-137 or Co-60 check source) or partner-lab beam time', qty: '1', note: 'Never buy an unlicensed source. If you cannot do this legally, use a partner lab' },
      { item: 'Geiger–Müller or NaI(Tl) scintillation detector with a 10-minute counting protocol', qty: '1', note: 'Report counts and Poisson uncertainty, not just a percentage (~$250)' },
      { item: 'Matched-areal-density reference plates: 6061 aluminium and a water cell', qty: '1 set', note: 'The comparison that makes the measurement meaningful (~$15/m)' },
      { item: 'Alkali melanin extraction kit (NaOH/DMSO) + spectrophotometer or EPR access', qty: '1 set', note: 'Quantify melanin in mg/g; otherwise you cannot attribute any effect to melanin' },
    ],
    buildSteps: [
      { title: 'Fabricate panels at three densities with melanin quantified', detail: 'Grow, dry and press three panel sets to nominal 100, 200 and 350 kg/m³. Measure dry density and thickness of every panel. Extract melanin by alkali solubilisation and report mg/g for each set, so any radiation effect can be attributed rather than assumed.' },
      { title: 'Commission the thermal rig against a known material', detail: 'Measure the 30 mm XPS reference and compare with its published k value. If you cannot reproduce it within about 10%, your thermocouples, guarding or steady-state criterion is wrong. Fix that before touching a mycelium panel.' },
      { title: 'Measure thermal conductivity at steady state', detail: 'Run each panel with a fixed ΔT across it, wait for the heat flux to stabilise for at least 30 minutes, and compute k = q·t/ΔT. Take three measurements per panel, and log ambient humidity — moisture content dominates the thermal result in an organic composite.' },
      { title: 'Measure mechanical strength and vacuum mass loss', detail: 'Three-point bend each panel to failure and report flexural strength and modulus. Then vacuum-cycle three specimens (pump down, hold, vent, repeat ten times) and weigh before and after. Outgassing and mass loss are the real space-qualification blockers, and they are cheap to measure.' },
      { title: 'Set up the attenuation experiment with matched areal density', detail: 'Weigh and cut a mycelium panel, an aluminium plate and a water cell to the same areal density (within 2%). Measure background, then source-through-nothing, then each sample, with identical geometry and 10-minute counts. Randomise the order and repeat to catch drift in the source or detector.' },
      { title: 'Report attenuation honestly with counting statistics', detail: 'Compute transmission ratios with Poisson error bars. Compare the mycelium result against the water prediction from μ/ρ ≈ 0.07 cm²/g at 1 MeV. If mycelium matches water, say so: the fungus is behaving as wet organic matter, and the melanin is not a radiation force field.' },
      { title: 'Write the "what is not proven" section', detail: 'Explicitly list: no neutron or charged-particle data measured here; no long-duration vacuum or UV survival data; no self-repair demonstrated; no dose-equivalent claim; melanin concentration not proven to be the active mechanism. That section is the point of the project.' },
    ],
    metrics: [
      { label: 'thermal conductivity', value: '0.04–0.06 W/(m·K) expected for 100–200 kg/m³ composite (measured; literature range)' },
      { label: 'melanin content', value: 'mg/g dry mass by alkali extraction (measured)' },
      { label: 'gamma transmission ratio vs aluminium at matched areal density', value: 'ratio with Poisson error bars (measured — will resemble water)' },
      { label: 'flexural strength', value: '0.1–1.5 MPa (measured; strongly process-dependent)' },
      { label: 'mass loss after 10 vacuum cycles', value: '% of dry mass, and % shrinkage (measured)' },
      { label: 'areal density of each panel', value: 'kg/m² to ±2% (measured)' },
    ],
    stretchGoals: [
      'Add a boron or lithium compound to a panel and test whether neutron moderation improves — this is the hypothesis with the most real upside.',
      'Measure k as a function of moisture content and produce a k-versus-RH curve for the composite.',
      'Run a 60-day UV exposure and measure melanin content and flexural strength before and after.',
      'Compare melanised and non-melanised panels at identical density and areal density; if the difference is inside the error bars, publish that.',
    ],
    safety: [
      'Never buy, borrow or improvise an unlicensed radioactive source. Use only a legal exempt-quantity check source in a locked, labelled container with a log book, or do the measurement at a licensed partner laboratory. A sealed source must never be opened, heated or disposed of in general waste.',
      'Melanin induction protocols may involve UV-B exposure and copper or tyrosine amendments. Never look at an operating UV lamp and never expose skin; use an enclosure with an interlock, UV-blocking goggles and gloves. Treat copper salts as toxic to aquatic life and dispose of them properly.',
      'Buy spawn from a commercial supplier and never culture wild moulds. Wear an N95/P2 respirator, gloves and eye protection when pressing, cutting or sanding dried panels — panel sanding is the peak spore-dust event.',
      'Anyone immunocompromised must not handle the panels or the incubation. Invasive aspergillosis is a documented risk from ordinary mould exposure in that group.',
      'Keep the incubation and pressing equipment on isolated low-voltage supplies with conformal coating; never run mains into the humid chamber. Autoclave or 10% bleach-soak all spent substrate for 30 minutes and dispose of it sealed.',
    ],
    lessonLinks: ['w7l14', 'w8l16', 'w8l15'],
    sources: [
      { label: 'bioRxiv — a self-replicating radiation shield for human deep-space exploration: radiotrophic fungi attenuate ionizing radiation aboard the ISS', url: 'https://www.biorxiv.org/content/10.1101/2020.07.16.205534v3' },
      { label: 'PNAS — radiation protection and structural stability of fungal melanin polylactic acid biocomposites in low Earth orbit', url: 'https://www.pnas.org/doi/10.1073/pnas.2427118122' },
      { label: 'ScienceDirect — mycelium-based composites for extreme environment engineering: from Earth to space', url: 'https://www.sciencedirect.com/science/article/pii/S2949929126000380' },
      { label: 'NASA NTRS — Mycotecture off planet: fungi as a building material on the Moon and Mars', url: 'https://ntrs.nasa.gov/citations/20210026908' },
      { label: 'PLOS ONE — protection of melanized Cryptococcus neoformans from lethal-dose gamma irradiation', url: 'https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0025092' },
    ],
  },

  {
    id: 'myc-advanced-magnetotactic',
    title: 'Ẹ̀rọ-Òfà — Magnetite-Bearing Fungal Magnetic Field Sensor',
    tagline: 'Fungi can biomineralise magnetite and magnetotactic bacteria navigate with it. Build the coil, grow the biomass, measure the magnetisation properly — then compare your biological transducer against a $10 commercial magnetometer.',
    category: 'mycelium',
    difficulty: 'orisha',
    buildTime: '8–12 weeks',
    costBand: '$$$',
    wakandaIndex: 80,
    diyFeasibility: 35,
    scienceGrounding: 42,
    realitySplit: {
      real: 'Biogenic magnetic nanoparticles and magnetosensitive inclusions are documented in microorganisms, and there is a real literature on magnetic iron minerals in fungi. Fungal pellets can also be loaded with ferromagnetic particles and actuated magnetically — a measured result, but additive, not biomineralisation. The physics of the sensor is calculable: a 50 nm single-domain magnetite crystal carries a moment of order 6 × 10⁻¹⁷ A·m², and a chain of twenty produces roughly 100 nT at 10 µm. Inducing magnetite, assaying iron by ICP-OES, measuring magnetisation on a VSM and establishing a null-corrected minimum detectable field is a genuine measurement programme.',
      narrative: 'A fungus that navigates by the geomagnetic field. Magnetotaxis is firmly established in magnetotactic bacteria and has never been demonstrated as a navigation mechanism in fungi. Any claim that a mycelium network senses magnetic north is speculative here and must be labelled as such. The honest deliverable is a sensitivity bound, which will almost certainly be far worse than a commodity sensor.',
    },
    summary: 'A four-part measurement programme rather than a sensor demo. Grow fungi on iron-amended substrate; quantify iron uptake by ICP-OES; measure the biomass magnetisation versus field on a VSM or SQUID at a partner lab, with the diamagnetic substrate background subtracted; and build a Helmholtz pair plus a sham coil to search for any reproducible growth or electrical response to a known 0–500 µT field. Then quote a minimum detectable field with a stated bandwidth and place it next to real commercial magnetometer noise floors.',
    science: 'Magnetite (Fe₃O₄) is ferrimagnetic with a saturation magnetisation near 480 kA/m, about 92 A·m²/kg. Below roughly 80 nm a magnetite crystal is a stable single domain and its moment is m = M_s·V; for a 50 nm cube that is ≈ 6 × 10⁻¹⁷ A·m². Its dipole field falls as r⁻³, B = μ₀m/(4πr³), giving about 1 nT at 20 µm for one crystal and about 100 nT at 10 µm for a twenty-crystal chain. That is exactly why magnetotactic bacteria work: their magnetosome chains are packed inside a cell a couple of micrometres across, so the field is strong precisely where a transducer would sit. A fungus has no such geometry. A mycelium mat is centimetres across, its iron is dispersed, and any added magnetic material is diluted by orders of magnitude in volume. So the achievable sensitivity is set by how much magnetite you concentrate and how close you can bring a transducer, not by any biological amplification. Quote the number with a stated bandwidth, and put it beside a fluxgate at pico-to-nanotesla per root hertz and an optically pumped magnetometer at femtotesla per root hertz. The comparison is the result.',
    billOfMaterials: [
      { item: 'Ganoderma lucidum or Pleurotus ostreatus spawn, 2 kg', qty: '1 bag', note: 'Commercial supplier; never wild isolates' },
      { item: 'Iron amendment: FeCl₃·6H₂O and FeSO₄·7H₂O, reagent grade', qty: '250 g each', note: 'Amend substrate at 0.1–2 g Fe/kg; treat as a chemical hazard' },
      { item: 'Helmholtz coil pair, 300 mm diameter, ~200 turns each, on a rigid non-magnetic frame', qty: '1 set', note: 'Uniform field region at the centre; calibrate with a magnetometer (~$180)' },
      { item: 'Constant-current coil supply, 0–5 A, with a current shunt and thermal cut-out', qty: '1 set', note: 'Coils get hot; derate and monitor temperature' },
      { item: 'QMC5883L/HMC5883-class magnetometer for coil calibration', qty: '1', note: 'Your $10 commercial baseline (~$6)' },
      { item: 'Tunnel-magnetoresistance (TMR) sensor board or a fluxgate module', qty: '1', note: 'The serious comparison sensor (~$40)' },
      { item: 'ESP32-S3 24-bit ADC logger + shielded twisted-pair cabling + μ-metal shield can', qty: '1 set', note: 'Hum and stray-field rejection (~$12)' },
      { item: 'Sealed non-magnetic sample holders (PTFE or fused silica)', qty: '6', note: 'Never a steel or nickel container' },
      { item: 'Magnetite reference powder, 99.9%, 1 g', qty: '1', note: 'Calibrate the VSM measurement chain and your own sensitivity floor' },
      { item: 'University service access: ICP-OES and VSM/SQUID magnetometry', qty: '1', note: 'Budget for beam time; this is the measurement that matters (~service access)' },
    ],
    buildSteps: [
      { title: 'Design the magnetic exposure experiment before growing anything', detail: 'Write the hypothesis, the sham control, the sample size and the falsification criterion first. Field strength 0, 50 and 500 µT; sham coil carrying current through a dummy load; at least six replicate plates per condition; temperature held identical. Without the sham, coil heating alone will produce a measurable growth effect and you will misread it as magnetoreception.' },
      { title: 'Grow with iron amendment and log growth rate', detail: 'Amend substrate at three iron levels, inoculate, and measure radial growth every 24 h for 14 days. Iron is a growth variable independently of any magnetic effect, so the zero-field iron series is a control, not an afterthought.' },
      { title: 'Assay iron uptake by ICP-OES', detail: 'Acid-digest dried biomass and substrate blanks and report Fe in mg/kg for every condition. Also report the substrate blank, because most of the iron you measure will be residual substrate and you must subtract it.' },
      { title: 'Measure magnetisation versus field on a VSM or SQUID', detail: 'Run hysteresis loops at 300 K from −1 T to +1 T on dried biomass and on a matched substrate blank. Report emu/g after background subtraction, with coercivity and remanence. If the loop is a straight line, you have no measurable ferromagnetic phase — that is a valid and publishable negative result.' },
      { title: 'Calibrate the Helmholtz pair and characterise your own noise floor', detail: 'Measure the actual field at the sample position with a calibrated magnetometer, then log your sensor for 60 minutes with no sample to establish the noise floor in the laboratory. Everything downstream is compared against that floor.' },
      { title: 'Run the null experiment on the living sample', detail: 'Place a colonised block in the coil centre with the sensor held at a fixed distance, and search for any reproducible change in the electrical or growth response as the field steps 0 → 500 → 0 µT. Run the identical schedule with the sham coil. Report the minimum detectable field with a stated bandwidth and averaging time.' },
      { title: 'Build the honest comparison table', detail: 'Columns: your fungal transducer, a QMC5883L-class magnetometer, a fluxgate, an OPM. Rows: sensitivity, noise per root hertz, bandwidth, power, cost, mass. State in one sentence which column a real application should choose, and why.' },
      { title: 'Publish the negative result as the headline', detail: 'The likely outcome is that the fungal system has no magnetotactic capability and the sensor is many orders of magnitude worse than a commodity chip. That is a genuinely useful, well-grounded result — treat it as the deliverable, not as a failure.' },
    ],
    metrics: [
      { label: 'iron content of biomass', value: 'mg/kg by ICP-OES after substrate-blank subtraction (measured)' },
      { label: 'saturation magnetisation', value: 'emu/g at 300 K on a VSM/SQUID; expect near-zero for unamended fungi (measured)' },
      { label: 'coercivity and remanence', value: 'Oe and emu/g; report whether a hysteretic phase exists at all (measured)' },
      { label: 'minimum detectable field of the living transducer', value: 'µT with stated bandwidth and averaging time (measured)' },
      { label: 'growth-rate change vs field with sham control', value: '% versus the sham coil, 6 replicates per condition (measured)' },
      { label: 'sensitivity gap vs a commercial magnetometer', value: 'orders of magnitude, stated explicitly (measured, compared)' },
    ],
    stretchGoals: [
      'Try a fungal species reported to biomineralise iron oxides and compare magnetisation per gram against Pleurotus.',
      'Concentrate the biomass magnetically before VSM measurement and see whether the magnetic fraction is enriched.',
      'Measure the biomass response to an AC field from 1 Hz to 1 kHz and look for any frequency-dependent dielectric or magnetic signature.',
      'Collaborate with a lab that has an optically pumped magnetometer and repeat the null experiment at femtotesla sensitivity.',
    ],
    safety: [
      'Iron salts are a chemical hazard: FeCl₃ is corrosive and stains everything, FeSO₄ is an irritant and an aquatic toxicant. Wear goggles, nitrile gloves and a lab coat, weigh them in a tray, and never dispose of them down a drain.',
      'Strong magnets and energised coils are hazardous to anyone with a pacemaker, ICD, cochlear implant or metal implant, and they erase cards and magnetise tools. Post a warning, keep magnets at least 1 m from such people, and secure the coil so it cannot be knocked over.',
      'Run the coil from a current-limited supply with a thermal cut-out and a fuse; coil wire gets hot enough to burn at sustained high current. Never leave an energised coil unattended, and never combine the wet incubation chamber with mains-powered coil wiring — separate circuits, separate enclosures.',
      'Buy spawn from a commercial supplier and never culture wild moulds. Wear an N95/P2 respirator and gloves when handling dry spawn or mouldy substrate, and exclude immunocompromised people from the workspace.',
      'Do not eat anything grown on iron-amended or otherwise amended experimental substrate. It is not food and the amendment dose is not a food-safety protocol.',
    ],
    lessonLinks: ['w2l3', 'w2l4', 'w5l10'],
    sources: [
      { label: 'NASU — biomineralization and synthesis of biogenic magnetic nanoparticles and magnetosensitive inclusions in microorganisms and fungi', url: 'https://nasplib.isofts.kiev.ua/items/b649ecd9-f8f5-42b2-9bae-b890d76affa0' },
      { label: 'KIT — magnetic actuation of fungal pellets via immobilization of ferromagnetic particles', url: 'https://publikationen.bibliothek.kit.edu/1000191246/176478995' },
      { label: 'arXiv:2403.11801 — magnetic properties of an individual Magnetospirillum gryphiswaldense cell', url: 'https://arxiv.org/abs/2403.11801' },
      { label: 'Phil. Trans. R. Soc. A — detection of endogenous magnetic nanoparticles with a tunnelling magnetoresistance sensor', url: 'https://royalsocietypublishing.org/doi/10.1098/rsta.2010.0137' },
    ],
  },

  {
    id: 'myc-advanced-mycoremediation',
    title: 'Ìmọ́-Ilẹ̀ — Mycelial Electrochemical Soil Remediation Rover',
    tagline: 'A slow rover that maps bioavailable heavy metals with square-wave voltammetry and inoculates the hotspot with spent mushroom substrate. The number that matters is extractable-metal change over twelve weeks against a control plot — and the fact that the metal never disappears.',
    category: 'mycelium',
    difficulty: 'journeyman',
    buildTime: '14–20 weeks (the biology sets the schedule)',
    costBand: '$$$',
    wakandaIndex: 82,
    diyFeasibility: 55,
    scienceGrounding: 58,
    realitySplit: {
      real: 'Mycoremediation is a real, published field: fungi biosorb and bioaccumulate metals, precipitate them as oxalates and phosphates, and change soil pH and organic-acid chemistry, and spent mushroom substrate has been shown to immobilise cadmium in trials. Square-wave anodic stripping voltammetry on screen-printed carbon electrodes is a mature portable method for Cd, Pb, Cu and Zn in solution, and portable XRF is the established field method for total soil metals. A rover that samples and doses at repeatable geotagged positions is exactly what a remediation trial needs.',
      narrative: 'A robot that cleans the soil. No reaction turns lead into something harmless — the metal stays in the system. Fungi change speciation and mobility, concentrate metal in biomass and immobilise some of it; if you do not harvest and correctly dispose of that biomass, much of the metal returns as it decays. The honest artefact is a controlled mass-balance field trial with a rover as the instrument platform.',
    },
    summary: 'A 5 kg rover that occupies a small randomised block trial: four replicated 1 × 1 m treatment plots and four controls, each sampled on a 0.25 m grid with a stainless auger, extracted on board, and analysed by square-wave anodic stripping voltammetry at the rover, with confirmatory ICP-OES in the lab. Between sampling rounds the rover dumps a measured dose of spent mushroom substrate and spawn slurry. Primary endpoint: DTPA-extractable Cd, Pb and Zn at 12 weeks against control. Secondary: total metal by XRF, biomass metal content, and a mass balance that accounts for every milligram.',
    science: 'Two numbers must never be confused. Total metal (mg/kg, by XRF or ICP after strong-acid digestion) describes the contamination and will barely move. Bioavailable or extractable metal (mg/kg, by a weak extract such as 0.01 M CaCl₂ or DTPA) describes what organisms can take up, and that is what mycoremediation can change. Fungi reduce bioavailability by binding metals to hyphal walls — chitin and chitosan are excellent biosorbents — by excreting oxalic and citric acid to form insoluble metal oxalates, by raising pH locally, and by storing metal in vacuoles and fruiting bodies. Reported results vary from no significant change to large reductions, with species, metal, soil pH, organic matter and time all mattering, so the only defensible design is a randomised block with four replicates per treatment, sampled before and at 2, 4, 8 and 12 weeks. Sampling depth and position repeatability must be controlled because extractable metal varies strongly over centimetres. At the end, harvest the fungal biomass, digest it and measure the metal. If the metal is neither in the soil nor in the biomass, you have lost it to leaching or to analytical error, and either way the mass balance is the finding.',
    billOfMaterials: [
      { item: '4WD rover chassis + ESP32 + motor drivers + RTK GNSS (u-blox NEO-M9N or better)', qty: '1 set', note: 'Positional repeatability is a measured metric, not an assumption' },
      { item: 'Stainless steel soil auger and core sampler, acid-washed', qty: '2', note: 'Steel tools contaminate trace-metal samples; use stainless or PTFE' },
      { item: 'Portable potentiostat (e.g. Squidstat Go) or a DIY LMP91000-class instrument', qty: '1', note: 'Square-wave anodic stripping voltammetry (~$2,500)' },
      { item: 'Screen-printed carbon electrode strips with a bismuth or mercury-free modification', qty: '100', note: 'Single-use; never re-use a contaminated electrode between plots (~$6 each)' },
      { item: 'Peristaltic dosing pump 12 V + 20 L tank + drop tube', qty: '1 set', note: 'Spawn slurry dosing at a logged rate per square metre (~$35)' },
      { item: 'Extractants: DTPA (0.005 M DTPA + 0.01 M CaCl₂ + 0.1 M TEA, pH 7.3) and 0.01 M CaCl₂', qty: '1 L each', note: 'Plus deionised water and clean HDPE bottles' },
      { item: 'pH/EC meter + handheld thermometer for soil conditions', qty: '1 set', note: 'pH drives metal mobility; log it with every sample' },
      { item: 'Spent mushroom substrate + Pleurotus ostreatus spawn, 60 kg total', qty: '1 set', note: 'Commercial supplier' },
      { item: 'Centrifuge or syringe filters (0.45 µm) + 15 mL PP tubes + cooler box', qty: '1 set', note: 'Filter within 30 minutes of extraction (~$200)' },
      { item: 'Shared-facility access: portable XRF and ICP-OES', qty: '1', note: 'Lab confirmation of the field voltammetry is mandatory, not optional (~service access)' },
    ],
    buildSteps: [
      { title: 'Lay out the trial as a randomised block before the rover moves', detail: 'Mark eight 1 × 1 m plots: four treatment, four control, randomly assigned, with a 0.5 m buffer. Record GPS coordinates to centimetre level and drive survey stakes. A remediation claim without a replicated control plot in the same soil is not a result.' },
      { title: 'Commission the voltammetry against certified standards', detail: 'Build calibration curves for Cd, Pb, Cu and Zn in the actual extractant matrix using certified standard solutions, over the range you expect. Report limit of detection, linearity and recovery. Matrix effects in DTPA are severe — a calibration in pure water will lie to you.' },
      { title: 'Characterise rover sampling repeatability', detail: 'Return the rover to ten marked points five times and measure positional error, auger depth error and the between-sample coefficient of variation of extractable Zn at a homogeneous spot. That coefficient of variation is your noise floor; any treatment effect must exceed it.' },
      { title: 'Run the week-0 baseline survey', detail: 'Sample five points per plot at 0–150 mm with the auger, extract with DTPA and 0.01 M CaCl₂, filter, and run voltammetry plus a lab ICP-OES split. Log total metal by XRF. Half your samples go to the lab as blind duplicates so you can quantify field-versus-lab disagreement.' },
      { title: 'Dose, and dose identically', detail: 'Apply spent mushroom substrate at a fixed rate (for example 2 kg/m²) plus 10% spawn by wet mass, tilled into the top 100 mm by hand or with the rover. Control plots receive the same physical disturbance and the same volume of sterile water, so the treatment difference is the fungus and its substrate, not the tilling.' },
      { title: 'Sample at weeks 2, 4, 8 and 12 on the same grid', detail: 'Return to the identical coordinates each round with the rover, sample the same depth, and log soil temperature, moisture and pH. This repeated-measures structure is what lets you separate a treatment effect from seasonal redox and rainfall effects.' },
      { title: 'Measure biomass metal and close the mass balance', detail: 'At week 12, harvest the fungal biomass from each treatment plot, weigh it, digest it, and measure metal by ICP-OES. Compute milligrams of metal removed from the extractable pool and compare with milligrams accumulated in biomass. Report the unaccounted fraction honestly — leaching, volatilisation and analytical error all live there.' },
      { title: 'Write the disposal and follow-up plan', detail: 'The metal-laden biomass is contaminated waste. State how it is packaged, labelled and disposed of, and specify how long the immobilisation lasts before the biomass decays and releases the metal again. That timeline is the real engineering question in mycoremediation.' },
    ],
    metrics: [
      { label: 'DTPA-extractable Cd, Pb, Zn', value: 'mg/kg dry soil; change at 12 weeks vs control with replicate spread (measured)' },
      { label: 'total metal by XRF', value: 'mg/kg; expect little change, and say so (measured)' },
      { label: 'field voltammetry vs lab ICP-OES agreement', value: 'bias and limits of agreement on blind duplicates (measured)' },
      { label: 'sampling repeatability', value: 'coefficient of variation at a homogeneous point, and positional error in mm (measured)' },
      { label: 'metal accumulated in fungal biomass', value: 'mg/kg and mg per plot by ICP-OES (measured)' },
      { label: 'mass balance closure', value: '% of the extractable-metal change accounted for by biomass uptake (measured)' },
    ],
    stretchGoals: [
      'Add a biochar-amended treatment arm and compare immobilisation against the fungal arm and their combination.',
      'Introduce a hyperaccumulating plant after inoculation and measure whether the fungus increases phytoextraction yield.',
      'Run the trial for 12 months to see how long immobilisation survives biomass decay.',
      'Use the rover to map extractable metal at 0.1 m resolution across a real contaminated site and publish the map.',
    ],
    safety: [
      'Contaminated soil is a chemical and carcinogenic hazard — cadmium and lead are cumulative toxins. Wear nitrile gloves, eye protection and an N95/P2 whenever soil is dry or being disturbed, never eat, drink or smoke on site, wash hands and forearms after work, and keep dedicated outerwear and tools that never enter the house.',
      'Acid and extractant handling: DTPA solutions and dilute nitric acid for digestion require goggles, a face shield for larger volumes, nitrile gloves, a chemical-resistant tray and an eyewash within reach. Never mouth-pipette anything, ever.',
      'Metal-laden fungal biomass and used electrodes are hazardous waste, not compost. Bag, label and dispose of them through a licensed hazardous-waste route, and never spread them on food crops or add them to a garden compost heap.',
      'Do not grow food on the experimental plots and do not eat anything harvested from them. Keep the trial at least 3 m from any vegetable bed or well, and check local rules before amending soil on a site you do not own — you may need permission for a soil amendment trial.',
      'Secure the rover: fuse the traction battery, guard the auger and the dosing tube, fit a latching emergency stop, and never service the auger with the battery connected. Keep all mains-powered lab equipment (centrifuge, potentiostat charger) out of the wet sampling area and never combine wet, contaminated soil with mains voltage.',
    ],
    lessonLinks: ['w6l11', 'w2l4', 'w7l14'],
    sources: [
      { label: 'Applied Ecology and Environmental Research — mycoremediation strategies for soil contamination: review of approaches and field limitations', url: 'https://www.aloki.hu/pdf/2402_19371962.pdf' },
      { label: 'Chemosphere 2023 — Hidalgo et al., combined mycoremediation and phytoremediation of contaminated soil', url: 'https://www.phytosudoe.eu/wp-content/uploads/2023/04/Hidalgo_2023_mycoremediation-phytoremediation.pdf' },
      { label: 'IAEA INIS — impact of spent mushroom substrate on Cd immobilisation and soil properties', url: 'https://inis.iaea.org/records/gj29p-nf181/files/DE20K7209.pdf' },
      { label: 'Recent advances in chemical sensors for soil analysis: a review (electrochemical and XRF field methods)', url: 'https://art.torvergata.it/retrieve/e291c0d9-d32e-cddb-e053-3a05fe0aa144/Recent%20Advances%20in%20Chemical%20Sensors%20for%20Soil%20Analysis-%20A%20Review_2022.pdf' },
      { label: 'Battelle — autonomous characterisation of contaminated soils using ground-based robotic platforms', url: 'https://www.battelle.org/docs/default-source/hidden/2023-bio-symp-abstracts/347.pdf' },
    ],
  },

  {
    id: 'myc-advanced-vibro-metamaterial',
    title: 'Ìdẹ́kun-Gbọ̀ǹgbọ̀n — Graded Mycelium Phononic Metamaterial for Robot Arms',
    tagline: 'A graded mycelium-composite lattice tuned to kill one vibration band in a small robot arm. Measure it with an accelerometer and an FFT — then measure the settling time, because that is the number your controller actually feels.',
    category: 'mycelium',
    difficulty: 'journeyman',
    buildTime: '6–9 weeks',
    costBand: '$$',
    wakandaIndex: 84,
    diyFeasibility: 58,
    scienceGrounding: 64,
    realitySplit: {
      real: 'Periodic and graded lattices have real, calculable band gaps: a periodic variation in stiffness and mass produces frequency ranges where waves do not propagate, and locally resonant unit cells produce narrow stop bands near their resonance. Mycelium composite is simultaneously stiff enough to be structural and lossy enough to damp — internal damping several times that of plywood or aluminium — which is a genuine advantage for broadband absorption. Arm settling time, accelerometer spectra and two-channel transfer functions are straightforwardly measurable with a low-noise accelerometer and a Python FFT.',
      narrative: 'A cloak that makes vibration vanish. A band gap is a stop band, not a force field: it removes energy in one designed window, does nothing outside it, and the compliant insert lowers arm stiffness and moves the arm\'s own resonances. You pay for damping with static deflection and positioning accuracy. The deliverable is the trade-off curve, not a claim of silence.',
    },
    summary: 'A graded mycelium-composite lattice insert for a small robot arm, built as three to six locally resonant unit cells with progressively different core masses. You measure the transmission from arm base to end effector with two accelerometers and a shaker or instrumented hammer, extract the band gap and the loss factor, and then measure the metrics a controller cares about: settling time to ±0.5 mm, first resonance frequency, and static tip deflection. An aluminium plate of matched mass and a solid mycelium pad of matched thickness are the controls.',
    science: 'Two mechanisms operate and should be separated. Bragg scattering opens a band gap when the unit-cell period is about half the wavelength; for a polymer composite with a wave speed of a few hundred metres per second that means 30–100 mm cells for a 40–200 Hz stop band, which is awkwardly large for an arm insert. Local resonance works differently: a heavy core on a compliant mycelium frame gives a narrow stop band near f = (1/2π)√(k/m), with the dip depth limited by the loss factor — exactly where a high-damping mycelium composite wins. Build a graded stack and measure the two-channel transfer function. Then measure the endpoint step response before and after: settling time to ±0.5 mm, first resonance, and static deflection under a 500 g tip load. A damper that halves settling time but triples deflection is not a win. Comparing against both an equal-mass aluminium plate and a solid mycelium pad separates the effect of lattice geometry from the effect of the material.',
    billOfMaterials: [
      { item: 'Pleurotus ostreatus or Trametes versicolor spawn + pasteurised hemp hurd', qty: '3 kg', note: 'Commercial spawn only' },
      { item: '3D-printed lattice moulds: graded log-pile or gyroid, 3 cell sizes', qty: '3 sets', note: 'PLA moulds are single-use if you demould wet' },
      { item: 'Steel or lead-free ballast cores (M4 washers or printed cavities filled with sand)', qty: '1 set', note: 'The local resonator mass; vary it per cell' },
      { item: 'ADXL355 low-noise accelerometer (or two IEPE accelerometers + charge amplifier)', qty: '2', note: 'One at the base, one at the end effector for a transfer function (~$55)' },
      { item: 'ESP32-S3 or a USB DAQ sampling at ≥3.2 kHz, with anti-alias filtering', qty: '1 set', note: 'You cannot FFT what you did not sample fast enough (~$12)' },
      { item: 'Voice-coil shaker or bass shaker + signal generator + 30 W amplifier', qty: '1 set', note: 'Or an instrumented impact hammer for a cheaper broadband excitation (~$60)' },
      { item: '500 g calibration mass + dial indicator (0.01 mm) + magnetic base', qty: '1 set', note: 'Static deflection and settling-time reference' },
      { item: '6061 aluminium plate of matched mass to the insert', qty: '1', note: 'Control column one: material effect (~$15/m)' },
      { item: 'Solid mycelium composite pad of matched thickness', qty: '1', note: 'Control column two: geometry effect' },
      { item: 'Small 3-DOF arm or single-joint test stand with a repeatable payload', qty: '1', note: 'Settling time needs a real closed-loop move' },
    ],
    buildSteps: [
      { title: 'Find the band you actually need to kill', detail: 'Mount the accelerometer at the end effector and run the arm through its real duty cycle. FFT the data and identify the dominant structural resonance in the 20–300 Hz range — for a small arm this is usually 40–150 Hz. Design for that measured band; designing for a guessed frequency is the most common way this project produces nothing.' },
      { title: 'Design and print graded lattice moulds', detail: 'Model three to six unit cells with the same outer envelope but different internal core masses, targeting local resonances spread across the problem band. Print the moulds with draft angles and split lines, and record the intended core mass and cell size for every cell.' },
      { title: 'Grow, dry and finish the inserts', detail: 'Fill the moulds to a consistent bulk density, incubate at 25 ± 2 °C for 10–14 days, demould and dry to constant mass at 60 °C. Log thickness and density of every insert and reject anything outside ±15%. Seal with shellac or linseed oil — a composite that absorbs water changes both mass and stiffness and invalidates your comparison.' },
      { title: 'Commission the measurement chain', detail: 'Calibrate both accelerometers against each other on a rigid block, measure the noise floor, and verify the sampling chain with a known sine from the signal generator. Compute a coherence function between the two channels and report it; coherence below about 0.9 means the transfer function is not trustworthy.' },
      { title: 'Measure transmission with a swept sine and an impact', detail: 'Sweep 10–500 Hz at moderate level with the shaker, and also strike with the instrumented hammer, averaging at least ten impacts. Compute the base-to-tip transfer function. Run it for the graded insert, the equal-mass aluminium plate, the solid mycelium pad, and no insert. Plot all four on one axis.' },
      { title: 'Extract the band gap and the loss factor', detail: 'Report the centre frequency and width of the stop band in Hz and the transmission loss in dB at the target band. Separately, tap the arm and fit the decay envelope to get the damping loss factor, so the reader can see how much of the attenuation is lattice geometry and how much is just material damping.' },
      { title: 'Measure the metrics the controller feels', detail: 'Command a 10° step and log the endpoint with the accelerometer, double-integrating to position or using a laser pointer on a scale. Report settling time to ±0.5 mm, overshoot, and static tip deflection under a 500 g load. Then report the same for the aluminium control. This is the honest comparison and it often reverses the spectral result.' },
      { title: 'Run a fatigue and humidity check', detail: 'Cycle the arm 20,000 times and re-measure the transfer function at 0, 25, 50 and 75% relative humidity. Mycelium composite stiffness and mass both drift with moisture, and a damper that only works in a dry lab is not a damper — it is a demonstration.' },
    ],
    metrics: [
      { label: 'transmission loss at the target band', value: 'dB from base to end effector (measured, all four configurations)' },
      { label: 'band-gap centre frequency and width', value: 'Hz, with coherence >0.9 stated for the band (measured)' },
      { label: 'damping loss factor', value: 'from log decrement; expect 0.05–0.15 for mycelium composite (measured)' },
      { label: 'arm settling time to ±0.5 mm', value: 'ms, with vs without the insert (measured — the decisive metric)' },
      { label: 'static tip deflection under 500 g', value: 'mm (measured; the cost of the compliance)' },
      { label: 'transfer function shift after humidity cycling', value: 'Hz and dB change at 25/50/75% RH (measured)' },
    ],
    stretchGoals: [
      'Add a 3D-printed Helmholtz-like side-branch resonator in front of the lattice and measure the extra low-frequency attenuation.',
      'Grow a lattice with a graded density (not just a graded core mass) by varying press pressure cell by cell.',
      'Close the loop: use the accelerometer signal to adapt a control gain as the insert ages and measure the compensation.',
      'Repeat with a hybrid insert — a thin aluminium skin over a mycelium core — and see whether the skin recovers stiffness without losing the damping.',
    ],
    safety: [
      'Buy spawn from a commercial supplier and never culture wild moulds. Discard any insert showing contamination, sealed and labelled.',
      'Wear an N95/P2 respirator, safety glasses and gloves for every demoulding, cutting and sanding step. Dry mycelium composite dust carries spores and resins, and sanding is the peak exposure event. Work outdoors or under HEPA extraction, never in a bedroom.',
      'A shaker at structural resonance can walk off a bench or launch loose fixtures. Clamp everything, keep the sweep level moderate, and wear safety glasses. A moving arm is a pinch and crush hazard: fit a guard and an e-stop before running settling-time tests.',
      'Sustained sweeps above 85 dB(A) damage hearing. Keep levels moderate, monitor at a distance, and use hearing protection for long test sessions.',
      'Exclude immunocompromised people from the workspace and keep all wet substrate work away from the electronics bench. Never combine wet organic substrate with mains voltage; run the arm and the shaker from properly fused, earthed supplies with the wet incubation physically separated.',
    ],
    lessonLinks: ['w2l3', 'w3l6', 'w4l8'],
    sources: [
      { label: 'Euronoise / FA2025 — measurements of the acoustic properties of mycelium-based materials using an impedance tube', url: 'https://dael.euracoustics.org/confs/fa2025/data/articles/000553.pdf' },
      { label: 'KU Leuven — acoustic characterisation of coffee-grounds-based mycelium composites', url: 'https://lirias.kuleuven.be/retrieve/b14bbb44-d657-4307-9f7e-9af7a16e01c2' },
      { label: 'Hu et al., AIP Advances 7, 025211 (2017) — acoustic metamaterials with coupled local resonators for broadband vibration suppression', url: 'https://pubs.aip.org/aip/adv/article/7/2/025211/21903/Acoustic-metamaterials-with-coupled-local' },
      { label: 'Mechanical Systems and Signal Processing — chatter suppression in robotic milling using horseshoe lattice acoustic metamaterials', url: 'https://www.sciencedirect.com/science/article/abs/pii/S0888327026006412' },
      { label: 'MDPI Machines 2024 — phononic and locally resonant lattice design for vibration control', url: 'https://www.mdpi.com/2075-1702/12/7/431' },
    ],
  },
];
