import type { ReferenceTable } from './types';

/**
 * The curated comparison tables for the /tables reference page.
 * Every row carries real values with units, real part numbers where useful,
 * and honest "~" markers on approximate figures.
 */
export const referenceTables: ReferenceTable[] = [
  {
    id: 'sensor-selection',
    title: 'Sensor selection for mobile robots',
    category: 'sensors',
    intro:
      'Every exteroceptive sense fails differently. Choose by the failure mode you can tolerate, then by range and rate — not by the headline specification.',
    columns: ['Sensor', 'Principle', 'Range', 'Resolution / accuracy', 'Rate', 'Interface', 'Approx. price', 'Best for', 'Failure mode'],
    rows: [
      ['HC-SR04', 'Ultrasonic time of flight, 40 kHz', '0.02–4 m', '~3 mm claimed, ±1% real', '~20 Hz', 'GPIO trig/echo', '$2', 'Cheap ranging, bin level', 'Soft or angled surfaces, crosstalk, wind, 60 ms blind time'],
      ['Sharp GP2Y0A21', 'IR triangulation', '0.10–0.80 m', 'Nonlinear, ~10%', '~50 Hz', 'Analog', '$8', 'Cliff and edge detection', 'Ambient sunlight, black surfaces, colour dependence'],
      ['VL53L0X / VL53L1X', 'dToF single point (VCSEL 940 nm)', '0.03–2 m (L0X) / 4 m (L1X)', '±5 mm typical', '30–50 Hz', 'I2C', '$5–12', 'Precise short range indoors', 'Strong IR sunlight, crosstalk with multiple units, glass'],
      ['TF-Luna / TFmini-S', 'Pulsed ToF LiDAR module', '0.2–8 m / 12 m', '±6 cm / ±1%', '100 Hz', 'UART / I2C', '$20–40', 'Altitude hold, obstacle stop', 'Rain, dust, retroreflective targets, low reflectivity at range'],
      ['RPLIDAR A1 / A2', '2-D spinning ToF (905 nm)', '0.15–12 m / 16 m', '~1% of range', '5.5–10 Hz scan', 'UART/USB', '$100–250', '2-D SLAM, mapping, AMR', 'Glass and mirrors, sunlight, black matte at range'],
      ['Livox Mid-360', 'Non-repetitive solid-state ToF', '0.1–40 m (70 m @ 80%)', '~2 cm', '200,000 pts/s', 'Ethernet', '$750', '3-D mapping, VIO', 'Rain, dust, cost, mount calibration'],
      ['Ouster OS0 / OS1', 'Spinning digital LiDAR, 32–128 beams', '0.3–50 m+', '~2–5 cm', '10–20 Hz frames', 'Ethernet', '$3k+', 'Autonomy-grade perception', 'Cost, weather, reflective surfaces'],
      ['Intel RealSense D435i / D455', 'Active IR stereo + IMU', '0.2–10 m / 0.4–20 m', '1–2% of depth at 1 m', '30–90 fps', 'USB 3', '$250–450', 'Manipulation, VIO, obstacle clouds', 'Sunlight, textureless or glossy surfaces, baseline limit'],
      ['mmWave radar IWR6843', 'FMCW 60 GHz, Doppler', '0.2–30 m', '~4 cm range, velocity direct', '20–30 Hz', 'UART/SPI', '$60–150', 'Robust detection through dust/rain', 'Angular resolution, clutter, calibration effort'],
      ['AS5600', 'Magnetic absolute angle (Hall)', '0–360°, 12-bit', '~0.09° (2^12)', '~1 kHz', 'I2C / analog / PWM', '$3', 'Joint angle sensing', 'Stray magnetic fields, off-axis placement error'],
      ['AS5048A', 'Magnetic absolute, 14-bit', '0–360°', '~0.02°', '~1 kHz', 'SPI / PWM', '$8', 'Precision joints', 'Field distortion, air-gap tolerance'],
      ['CUI AMT102', 'Capacitive incremental', 'Incremental', '4096 PPR', 'up to 8 kHz', 'A/B quadrature', '$25', 'Motor feedback, rugged', 'Needs homing, dust in the gap'],
      ['MPU6050', 'MEMS accel + gyro', '±2–16 g, ±250–2000 °/s', 'Gyro noise ~0.005 °/s/√Hz', '1 kHz', 'I2C', '$3', 'Cheap attitude, vibration logging', 'Bias drift, temperature sensitivity, no magnetometer'],
      ['ICM-42688-P', 'Low-noise MEMS IMU', '±16 g, ±2000 °/s', '~2.8 mdps/√Hz', 'up to 32 kHz', 'SPI / I2C', '$10', 'Serious VIO and stabilisation', 'Needs thermal calibration for best bias stability'],
      ['BNO055', 'Fused IMU + magnetometer with on-chip fusion', '±16 g, ±2000 °/s', '~1° heading (clean field)', '100 Hz', 'I2C / UART', '$25', 'Fast prototyping without fusion code', 'Magnetic disturbance, calibration staleness, internal fusion is a black box'],
      ['VectorNav VN-100', 'Industrial IMU/AHRS', '±16 g, ±2000 °/s', 'Heading ~0.5°, pitch/roll ~0.1°', '400 Hz', 'UART/SPI', '$1.5k+', 'Field robotics, calibrated AHRS', 'Cost, magnetometer still hates motors'],
      ['INA219 / ACS712', 'Shunt current sense', '±3.2 A / ±5–30 A', '±0.5% (INA219)', '~1 kHz', 'I2C / analog', '$3–8', 'Power budgeting, stall detection', 'Burden voltage, thermal drift, noisy grounding'],
      ['u-blox NEO-M9N / ZED-F9P', 'GNSS / RTK GNSS', 'Global / ~1 cm RTK', '~1.5 m / ~1 cm + 1 ppm', '1–20 Hz', 'UART / USB / SPI', '$40 / $220', 'Outdoor localisation, RTK survey', 'Urban canyons, trees, spoofing, no indoor use, fix loss'],
    ],
    insight:
      'Rank sensors by what happens when they lie, not by how good they are when they work. A GNSS jump in an urban canyon and a LiDAR return from a mirror both produce confident, wrong data — which is why the filter in the Kalman lab matters more than the sensor datasheet.',
  },
  {
    id: 'actuator-selection',
    title: 'Actuator selection',
    category: 'actuators',
    intro:
      'Torque, speed, backlash and heat are a four-way trade. Pick the actuator family from the control problem first: position, velocity, force or compliance.',
    columns: ['Actuator', 'Principle', 'Torque', 'Speed', 'Efficiency', 'Backlash', 'Control', 'Approx. price', 'Use case'],
    rows: [
      ['SG90 micro servo', 'Brushed DC + plastic gear + internal position loop', '~1.8 kg·cm at 4.8 V', '~0.1 s/60°', '~40%', '2–5° typical', 'PWM 50 Hz', '$3', 'Pan-tilt, small fins, teaching'],
      ['MG996R servo', 'Brushed DC + metal gears', '~10 kg·cm at 6 V', '~0.17 s/60°', '~50%', '~1–2°', 'PWM 50 Hz', '$12', 'Steering, medium grippers, hobby arms'],
      ['Dynamixel XM430-W350', 'BLDC + planetary, smart serial', '3.0 N·m stall, 1.0 N·m cont.', '~46 rpm at 12 V', '~70%', '< 0.5°', 'TTL/RS-485, position/velocity/current', '$300', 'Quadrupeds, research arms, force control'],
      ['Geared brushed DC (12 V, 1:50)', 'Brushed DC + spur/planetary', '~2.4 N·m stall', '~120 rpm no load', '60–75%', '1–3°', 'PWM + encoder', '$20–60', 'Cheap mobile bases, conveyors'],
      ['Hoverboard hub motor (6.5 in)', 'BLDC direct drive', '~28 N·m stall', '~500 rpm', '80–88%', 'Minimal', 'FOC, Hall sensors', '$35–60', 'Wheeled robots, self-balancing bases'],
      ['BLDC 6374 + ODrive', 'Outboard BLDC with FOC driver', '1–3 N·m continuous', 'up to 8000 rpm', '85–92%', 'None (direct)', 'FOC, torque or velocity mode', '$120 motor + $150 driver', 'Legged joints, direct-drive wheels'],
      ['NEMA17 stepper + TMC2209', 'Stepper, microstepped', '~0.4 N·m holding', '~300 rpm usable', '50–70%', 'None (but loss of sync)', 'Step/dir, UART config', '$15 + $10', '3D printers, CNC, camera sliders'],
      ['Linear actuator (12 V)', 'DC motor + lead screw/nut', '50–500 N', '10–50 mm/s', '50–70%', '~0.5 mm', 'PWM + limit switches', '$40–120', 'Lifting, hatches, linear stages'],
      ['Pneumatic cylinder', 'Compressed air pressure', 'F = P·A, e.g. 480 N at 6 bar, 32 mm bore', '0.1–1 m/s', 'Low overall (compressor)', 'Cushioned', 'Solenoid valves / proportional', '$30 + compressor', 'Fast pick-and-place, soft robotics'],
      ['McKibben artificial muscle', 'Braided mesh + bladder', 'F = (π D²/4) P (3cos²θ − 1)', 'Fast contraction, ~25% stroke', 'Low overall', 'Compliant', 'PWM valves / pressure', '$20–60', 'Soft grippers, assistive devices'],
      ['Piezo bender', 'Inverse piezoelectric effect', 'mN·m, µN·m', 'Very fast, kHz', 'High at resonance', 'None', 'High-voltage amplifier', '$10–100', 'Micro-manipulation, ultrasonic motors'],
      ['Shape memory alloy (Nitinol)', 'Thermal phase change', 'Moderate force, low stroke', '0.1–1 Hz', '< 10%', 'None', 'Current PWM, hysteresis', '$5–20', 'Lightweight micro-actuators, morphing'],
      ['Series elastic actuator', 'Motor + deliberate spring', 'Motor torque through spring', 'Bandwidth limited by spring', '60–80%', 'Spring compliance', 'Force control via deflection', '$500+', 'Legged robots, safe human contact'],
      ['Cycloidal joint module', 'BLDC + cycloidal reducer', '20–100 N·m', '10–40 rpm out', '80–90%', 'Low', 'FOC + absolute encoder', '$1k+', 'Legged knees, high shock loads'],
    ],
    insight:
      'If you cannot state the continuous torque, the duty cycle and the maximum joint speed, you are not ready to order. Backlash and efficiency decide whether the machine feels precise; thermal margin decides whether it survives the afternoon.',
  },
  {
    id: 'compute-platforms',
    title: 'Compute platforms for robots',
    category: 'compute',
    intro:
      'Split compute by determinism. A microcontroller owns the hard real-time loop and the safety chain; a Linux companion owns perception and planning.',
    columns: ['Board', 'CPU', 'Clock', 'RAM / flash', 'Hard real-time?', 'AI acceleration', 'Typical power', 'Approx. price', 'Best for'],
    rows: [
      ['Arduino Uno R3', 'ATmega328P', '16 MHz', '2 KB / 32 KB', 'Yes (bare metal)', 'None', '~50 mW', '$25', 'Teaching, single-sensor nodes'],
      ['Raspberry Pi Pico / RP2040', 'Dual Cortex-M0+', '133 MHz', '264 KB / 2 MB', 'Yes, plus PIO state machines', 'None', '~100 mW', '$4', 'Motor control, custom protocols, cheap multi-axis'],
      ['ESP32-S3', 'Dual LX7 + ULP', '240 MHz', '512 KB + PSRAM / 8 MB', 'Good, but Wi-Fi adds jitter', 'Vector extensions for light inference', '~0.5 W active, ~10 µA deep sleep', '$8', 'Connected robots, MQTT, micro-ROS'],
      ['STM32F411', 'Cortex-M4F', '100 MHz', '128 KB / 512 KB', 'Excellent with timers + DMA', 'None', '~100 mW', '$12', 'Serious fixed-rate control loops'],
      ['Teensy 4.1', 'Cortex-M7', '600 MHz', '1 MB / 8 MB', 'Very good, watch cache jitter', 'None', '~0.5 W', '$30', 'High-rate control, many encoders'],
      ['Portenta H7', 'Dual M7 + M4', '480 MHz / 240 MHz', '1 MB / 2 MB', 'Yes (M4 core)', 'None', '~1 W', '$100', 'Industrial-ish MCU work, dual-core partitioning'],
      ['Raspberry Pi 5', 'Quad Cortex-A76', '2.4 GHz', '4–8 GB / microSD or NVMe', 'No (Linux scheduling)', 'None (add a HAT)', '3–8 W', '$60–90', 'ROS 2, vision, fleet software'],
      ['Google Coral Dev Board', 'Cortex-A53 + Edge TPU', '1.5 GHz', '1–4 GB', 'No', '4 TOPS INT8 Edge TPU', '2–5 W', '$130', 'Quantised on-device inference'],
      ['Jetson Orin Nano', '6× Cortex-A78AE + Ampere GPU', '1.5 GHz', '8 GB', 'No', '~40 TOPS INT8 (Super mode)', '7–15 W', '$200–250', 'Multi-camera perception, SLAM, learned policies'],
      ['Jetson Orin NX / AGX Orin', '8–12× A78AE + Ampere GPU', '2.0 GHz', '16–64 GB', 'No', '70–275 TOPS', '15–60 W', '$400–2000', 'Autonomy-grade perception, robotaxi-class stacks'],
    ],
    insight:
      'The classic split is a $10 microcontroller plus a $250 Jetson, not one board doing both. The microcontroller guarantees the loop and the e-stop path; the Jetson gets to be slow and clever without endangering anyone.',
  },
  {
    id: 'comms-protocols',
    title: 'Communication protocols',
    category: 'comms',
    intro:
      'Choose by topology, distance and determinism. Most robot bugs blamed on control loops are actually bus timing problems.',
    columns: ['Protocol', 'Layer / type', 'Data rate', 'Range', 'Topology', 'Determinism', 'Power', 'Typical robot use'],
    rows: [
      ['UART', 'Point-to-point serial', '9.6 kbit/s – 5 Mbit/s', '< 1 m on board, longer over RS-232', 'Two devices', 'Good if not blocking', 'Low', 'GNSS, LiDAR modules, debugging'],
      ['I2C', 'Multi-drop, 2 wires', '100 kHz – 3.4 MHz', '< 1 m typically', 'Up to ~112 devices, addressed', 'Clock stretching breaks timing', 'Low', 'IMUs, EEPROMs, small sensors'],
      ['SPI', 'Multi-drop, 4 wires', '1–50 Mbit/s', '< 0.3 m', 'One chip select per device', 'Very good, full duplex', 'Low', 'IMU at 1 kHz, SD cards, ADCs'],
      ['RS-485', 'Differential multidrop serial', 'up to 10 Mbit/s short, 100 kbit/s at 1.2 km', 'up to 1200 m', 'Multi-drop bus', 'Good', 'Low', 'DMX, industrial sensors, long runs'],
      ['CAN / CAN-FD', 'Differential, arbitrated', '1 Mbit/s / 5–8 Mbit/s', 'up to 1 km at low rate, 40 m at 1 Mbit/s', 'Multi-master bus', 'Deterministic arbitration by ID', 'Low', 'Joint buses, battery BMS, automotive'],
      ['EtherCAT', 'Industrial Ethernet', '100 Mbit/s', '100 m per segment', 'Line/ring, hundreds of nodes', 'Microsecond-level sync', 'Moderate', 'Multi-axis machine control'],
      ['USB 2.0 / 3.x', 'Host-device serial', '480 Mbit/s / 5–20 Gbit/s', '5 m passive', 'Star via hubs', 'Isochronous modes exist', 'Moderate', 'Cameras, LiDAR, serial adapters'],
      ['Ethernet / TSN', 'Packet switched', '100 Mbit/s – 10 Gbit/s', '100 m copper', 'Star / mesh', 'TSN adds bounded latency', 'Moderate', 'LiDAR, ROS 2, camera streams'],
      ['Wi-Fi 6', 'Wireless LAN', 'up to ~600 Mbit/s real', '30–100 m indoor', 'Infrastructure / mesh', 'Best effort, variable latency', 'High', 'Telemetry, teleoperation, OTA'],
      ['BLE 5', 'Wireless PAN', '1–2 Mbit/s', '10–50 m', 'Star / mesh (BLE Mesh)', 'Connection intervals 7.5 ms+', 'Very low', 'Configuration, wearables, beacons'],
      ['Zigbee / Thread / Matter', 'Wireless mesh', '250 kbit/s', '10–100 m per hop', 'Mesh', 'Best effort', 'Very low', 'Building sensors, smart agriculture'],
      ['LoRaWAN', 'LPWAN, chirp spread spectrum', '0.3–50 kbit/s', '2–15 km rural', 'Star of stars', 'Duty-cycle limited', 'Very low', 'Field telemetry, soil sensors, livestock'],
      ['NB-IoT / LTE-M', 'Cellular LPWAN', '20–250 kbit/s', 'Cellular coverage', 'Star', 'Scheduled, licensed band', 'Low', 'Remote assets without a gateway'],
      ['5G (URLLC)', 'Cellular', '100+ Mbit/s, ~1 ms target latency', 'Cellular', 'Star', 'Designed for bounded latency', 'High', 'Teleoperation, dense fleets, private campus'],
      ['MQTT', 'Application protocol over TCP', 'Depends on transport', 'Any', 'Broker-mediated publish/subscribe', 'QoS 0/1/2 delivery guarantees', 'Low', 'Fleet telemetry, command topics'],
      ['CoAP', 'Application protocol over UDP', 'Depends on transport', 'Any', 'Client/server, REST-like', 'Confirmable messages', 'Very low', 'Constrained devices, sleepy nodes'],
      ['DDS (ROS 2 default)', 'Publish/subscribe middleware', 'Depends on transport', 'Any', 'Peer to peer with discovery', 'Configurable QoS: reliability, deadline, liveliness', 'Moderate', 'Intra-robot and multi-robot data flow'],
    ],
    insight:
      'Latency budgets are sums, not averages. Add sensor acquisition, bus transfer, middleware hop, compute and actuator response, then compare against your deadline with margin. If the sum is close, the design is already late.',
  },
  {
    id: 'power-sources',
    title: 'Power sources, from battery to exotic harvesting',
    category: 'power',
    intro:
      'Orders of magnitude matter more than elegance. Know what each source can actually run before you design the load.',
    columns: ['Source', 'Principle', 'Practical power density', 'Energy density', 'DIY feasibility', 'Safety / legal risk', 'Robotics use case'],
    rows: [
      ['Li-ion / LiPo cell', 'Lithium intercalation', '250–1000 W/kg', '150–265 Wh/kg', 'High, but needs a BMS and respect', 'Fire on overcharge/puncture, transport rules', 'The default for anything mobile'],
      ['LiFePO4', 'Lithium iron phosphate', '200–600 W/kg', '90–140 Wh/kg', 'High', 'Much safer thermally, lower energy density', 'Fixed installations, long-cycle robots'],
      ['NiMH', 'Nickel metal hydride', '~250 W/kg', '60–120 Wh/kg', 'High', 'Low risk, memory effects mild', 'Toys, backup, low-cost packs'],
      ['Lead-acid', 'Sulphuric acid chemistry', '~180 W/kg', '30–50 Wh/kg', 'High', 'Acid, hydrogen venting, heavy', 'Warehouse AGVs where mass is an asset'],
      ['Supercapacitor', 'Electrostatic double layer', '10,000+ W/kg bursts', '3–10 Wh/kg', 'High', 'Low voltage per cell, needs balancing', 'Regenerative braking buffers, peak assist'],
      ['Solar (outdoor)', 'Photovoltaic, 1000 W/m² STC', '150–230 W/m² at 20% efficiency', 'n/a (harvesting)', 'High', 'Low risk; eye safety when concentrating', 'Field robots, agri sensors, habitats'],
      ['Solar (indoor)', 'Photovoltaic under 1–10 W/m²', '0.1–2 mW/cm² depending on lux and cell', 'n/a', 'High', 'None', 'Indoor sensor nodes only'],
      ['Thermoelectric (TEG)', 'Seebeck effect across ΔT', '~5 W per 40×40 mm module at ΔT 100 K', 'n/a', 'Moderate: needs a real heat source and sink', 'Hot surfaces, burn risk', 'Geothermal probes, exhaust/compost harvesting, RTGs in space'],
      ['Piezoelectric', 'Strain-induced polarisation', '~5 mJ per footstep, mW average', 'n/a', 'Moderate', 'High voltage spikes, brittle ceramics', 'Insole chargers, vibration sensors, road tiles'],
      ['Triboelectric (TENG)', 'Contact electrification', 'kV output at µA, mW/m²', 'n/a', 'Moderate', 'Static discharge, EMI', 'Self-powered touch and motion sensing'],
      ['RF / ambient EM harvesting', 'Rectenna at 900 MHz–2.4 GHz', 'µW at typical ambient levels', 'n/a', 'Moderate', 'None', 'Battery-free tags and switches'],
      ['Plant microbial fuel cell', 'Rhizodeposition + electrogenic bacteria', '~10–200 mW per m² of electrode', 'n/a', 'High for a hobby build', 'Biofouling, no hazard', 'Trickle-charged wetland sensors'],
      ['Atmospheric / electrostatic', 'Fair-weather potential gradient', '~1–10 µW from a tall collector; conduction current ~1–3 pA/m²', 'n/a', 'Moderate, but returns almost nothing', 'Lightning risk if you go tall or high', 'Wake-timer nodes at best; a teaching example in honest limits'],
      ['Telluric / geoelectric', 'Natural Earth currents', 'µW–mW with long electrode spans (mV/km signals)', 'n/a', 'Moderate', 'Electrode chemistry, long cables', 'Geophysical sensing, not power'],
      ['Betavoltaic', 'Beta particles to semiconductor junction', 'µW–mW per cm³ over decades', 'Very high for micro-loads', 'Not DIY', 'Radioactive source, licensing', 'Implantable and remote micro-sensors'],
      ['RTG (radioisotope)', 'Pu-238 decay heat + thermocouples', 'MMRTG: 110 W electrical, ~2000 W thermal, 45 kg (~5.5% efficient)', 'Decades of life', 'Not DIY', 'Nuclear material, launch licensing', 'Deep-space and sun-poor planetary missions'],
      ['Fission surface power', 'Nuclear fission + Stirling/Brayton', 'NASA KRUSTY demonstrated 1–10 kWe class', 'Years of life', 'Not DIY', 'Nuclear, export control', 'Lunar/Mars surface bases, high-power habitats'],
    ],
    insight:
      'Read this table left to right as a lesson in humility: harvesting sources live three to six orders of magnitude below a lithium cell. Design the load to the source — a 50 µW wake-timer radio can run on atmospheric charge, a 5 W servo never will.',
  },
  {
    id: 'control-methods',
    title: 'Control methods',
    category: 'control',
    intro:
      'Every method is a trade between model accuracy, compute and robustness. Start with PID and add structure only when you can name the failure it fixes.',
    columns: ['Method', 'Needs a model?', 'Compute cost', 'Robustness', 'Tuning effort', 'Best for', 'Watch out for'],
    rows: [
      ['Bang-bang', 'No', 'Trivial', 'Low', 'Very low', 'Heaters, simple thermostats', 'Limit cycling, actuator wear'],
      ['PID', 'No (linear intuition)', 'Very low', 'Moderate', 'Low–moderate', 'Velocity, position, temperature, altitude', 'Integral windup, derivative noise, delays'],
      ['Cascade PID', 'No', 'Low', 'Good', 'Moderate', 'Position to velocity to current chains', 'Inner loop must be much faster than outer'],
      ['Feedforward + PID', 'Rough model or lookup', 'Low', 'Good', 'Moderate', 'Trajectory tracking, gravity compensation', 'Model errors show up as steady-state offset'],
      ['LQR', 'Yes (linear state space)', 'Low–moderate', 'Moderate', 'Moderate (weights)', 'Balancing, multi-state regulation', 'Linearisation valid only near the operating point'],
      ['MPC', 'Yes, needs prediction model', 'High', 'Good with constraints', 'High', 'Constraint-rich problems, UAV and vehicle control', 'Solve time, feasibility, tuning the cost'],
      ['Sliding mode', 'Partial', 'Low–moderate', 'Very high', 'Moderate', 'Systems with matched disturbances', 'Chattering, needs boundary layer or higher order'],
      ['Adaptive control', 'Yes with parameter update', 'Moderate', 'High to slow variation', 'High', 'Payload and wear variation', 'Stability proof required; can diverge'],
      ['Gain scheduling', 'Yes (a family of linear models)', 'Low', 'Good', 'Moderate', 'Nonlinear plants with distinct regimes', 'Discontinuities between schedules'],
      ['Fuzzy logic', 'No', 'Low', 'Moderate', 'High (rule count)', 'Expert heuristics, non-analytic plants', 'No guarantees, rule explosion'],
      ['Impedance / admittance', 'Robot kinematics + dynamics', 'Moderate', 'Good for contact', 'High', 'Physical interaction, assembly, cobots', 'Contact stability depends on stiffness and delay'],
      ['Force control', 'Dynamics of contact', 'Moderate', 'Moderate', 'High', 'Polishing, deburring, insertion', 'Contact transitions, stiction, sensor drift'],
      ['Computed torque', 'Full dynamics model', 'High', 'Good with an accurate model', 'Moderate', 'High-speed manipulators', 'Model error and payload change degrade it'],
      ['Learned policy (RL / imitation)', 'Learned from data', 'Moderate–high at inference', 'Unclear outside training distribution', 'Very high (data and reward design)', 'Tasks that resist analytic modelling', 'No guarantees, sim2real gap, reward hacking, unverifiable failure'],
    ],
    insight:
      'The professional sequence is: get PID working, add feedforward, add a model-based method only where you can point at the physical limitation it fixes. Every added structure is a new way to fail.',
  },
  {
    id: 'gearbox-types',
    title: 'Gearbox types',
    category: 'actuators',
    intro:
      'Ratios are cheap; backlash, efficiency and self-locking are what you actually pay for. Match the gearbox to the axis, not to the catalogue.',
    columns: ['Type', 'Ratio range', 'Backlash', 'Efficiency per stage', 'Torque density', 'Self-locking', 'Approx. cost', 'Best for'],
    rows: [
      ['Spur', '1:1 – 1:8', 'Moderate (0.5–2°)', '96–98%', 'Moderate', 'No', '$', 'Cheap reductions, printed robots, idlers'],
      ['Helical', '1:1 – 1:10', 'Moderate', '95–98%', 'Higher than spur', 'No', '$$', 'Quieter and stronger spur replacement'],
      ['Bevel', '1:1 – 1:5', 'Moderate', '93–97%', 'Moderate', 'No', '$$', 'Right-angle drive, differentials'],
      ['Worm', '1:5 – 1:100', 'Low', '40–85%', 'High at low ratio', 'Usually yes', '$–$$', 'Holding vertical loads without power'],
      ['Planetary', '1:3 – 1:100', 'Low (0.2–1°)', '90–97%', 'High', 'No', '$$', 'NEMA-frame reductions, wheel drives'],
      ['Harmonic / strain wave', '1:30 – 1:320', 'Near zero (< 1 arcmin)', '65–85%', 'Very high', 'No', '$$$$', 'Cobot joints, precision wrists'],
      ['Cycloidal', '1:10 – 1:200', 'Low', '80–92%', 'Very high', 'No', '$$$', 'Legged robot knees, shock loads'],
      ['Belt / timing belt', '1:1 – 1:5', 'Low but compliant', '94–98%', 'Moderate', 'No', '$', 'Quiet, long-distance transfer, GT2/GT3 stages'],
      ['Chain', '1:1 – 1:6', 'Moderate', '92–98%', 'Moderate', 'No', '$', 'Rugged transfer, tank drives'],
      ['Cable / capstan', 'Any (with reduction)', 'Very low with preload', '85–95%', 'High', 'No', '$$', 'Remote actuation, continuum and tendon arms'],
    ],
    insight:
      'Backlash hurts repeatability, not average accuracy. A 1° backlash axis can be accurate on average and useless for a 0.1° insert — and the fix is usually a harmonic drive or a preloaded cable stage, not better software.',
  },
  {
    id: 'mycelium-substrates',
    title: 'Mycelium biocomposite recipes and growth parameters',
    category: 'biology',
    intro:
      'Published values vary by an order of magnitude because process dominates. Treat these as starting points and always report your own substrate, spawn ratio, press pressure and drying schedule with the result. Numbers marked ~ are typical literature ranges, not guarantees.',
    columns: ['Substrate', 'Spawn ratio', 'Moisture', 'Colonisation', 'Press', 'Dry / deactivate', 'Density', 'Compressive strength', 'Notes'],
    rows: [
      ['Hemp hurd', '~20–30% spawn by mass', '~60–75%', '~10–21 days at 24–27 °C', '~0.5–2 MPa', '~60–80 °C until constant mass', '~150–350 kg/m³', '~0.20–0.80 MPa', 'Best all-round structural substrate; good insulation'],
      ['Hardwood sawdust', '~20–30%', '~55–70%', '~14–28 days', '~0.3–1 MPa', '~60–80 °C', '~180–400 kg/m³', '~0.15–0.70 MPa', 'Slower colonisation, denser, good for blocks'],
      ['Wheat/rice straw', '~20–30%', '~60–75%', '~10–20 days', '~0.2–0.8 MPa', '~60–80 °C', '~100–250 kg/m³', '~0.10–0.40 MPa', 'Cheap, excellent acoustic absorption, weaker in bending'],
      ['Spent coffee grounds', '~15–25%', '~55–65%', '~7–14 days (fast)', '~0.2–0.6 MPa', '~60–80 °C', '~200–450 kg/m³', '~0.15–0.60 MPa', 'Fast growth, contamination-prone, needs sterilisation'],
      ['Corrugated cardboard', '~20–30%', '~60–70%', '~10–18 days', '~0.2–0.6 MPa', '~60–80 °C', '~120–280 kg/m³', '~0.10–0.35 MPa', 'Free feedstock, low strength, great for packaging'],
      ['Corn stover / agri waste', '~20–35%', '~60–75%', '~12–24 days', '~0.3–1 MPa', '~60–80 °C', '~130–320 kg/m³', '~0.12–0.50 MPa', 'Regionally abundant; properties vary widely by species'],
      ['Cotton gin trash / husk', '~20–35%', '~55–70%', '~12–25 days', '~0.3–1 MPa', '~60–80 °C', '~150–350 kg/m³', '~0.15–0.45 MPa', 'Silica content can blunt tools'],
      ['Mycelium + natural binder (mycocrete-type)', '~15–25% plus binder', 'Workability-controlled', '~7–14 days then cast', 'Cast, not pressed', '~60–80 °C', '~300–600 kg/m³', '~0.4–1.2 MPa', 'Castable forms; higher strength, higher density, more process control needed'],
    ],
    insight:
      'Density and strength move together, and both follow the press. If you need stiffness, press harder and accept mass; if you need insulation, press lightly and accept that it will dent. Deactivation is not optional — a live composite keeps growing, loses dimensions and eventually fruits indoors.',
  },
  {
    id: 'living-materials',
    title: 'Living and bio-hybrid materials for robotics',
    category: 'biology',
    intro:
      'Living components buy self-repair, environmental sensitivity and compostability at the cost of speed, repeatability and predictability. Read the TRL column as a statement about evidence, not ambition.',
    columns: ['Material', 'Organism / mechanism', 'What it does', 'Response time', 'Lifespan', 'Integration', 'TRL', 'Ethics / biosafety'],
    rows: [
      ['Mycelium biocomposite', 'Pleurotus, Ganoderma, Trametes on agri waste', 'Structural panels, chassis, acoustic and thermal insulation', 'Days to grow, then inert', 'Years once deactivated; weeks if alive', 'Bolted or bonded like wood; moisture barrier needed', '5–7', 'Buy spawn from reputable suppliers; N95 when handling dry spawn; never culture unknown wild mould'],
      ['Fungal electrical sensing', 'Hyphal membrane potentials and ion channels', 'Slow chemical and mechanical sensing via spike activity', 'Seconds to minutes per spike', 'Days to weeks per culture', 'High-impedance electrodes, INA333/AD620 front end, guarded wiring', '2–3', 'Contamination control; keep wet substrate away from mains; no claim of cognition'],
      ['Bacterial cellulose', 'Komagataeibacter in sugar media', 'Tough, mouldable hydrogel sheets and acoustic membranes', 'Days to weeks', 'Months if kept hydrated', 'Dried sheets behave like stiff paper', '3–4', 'Sterile technique, sealed vessels, autoclave waste'],
      ['Engineered living materials', 'Genetically modified bacteria or yeast', 'Programmable material deposition, sensing, self-healing', 'Hours to days', 'Days to weeks', 'Needs containment and a nutrient supply', '2–4', 'Containment, kill switches, no antibiotic-resistance markers outside a licensed lab'],
      ['Microbial fuel cell', 'Electrogenic bacteria on a carbon-felt anode', 'Trickle power from organic matter, ~10–200 mW/m²', 'Minutes to hours', 'Months with feeding', 'Anode/cathode in soil or wastewater, load management essential', '3–5', 'Fouling, non-hazardous, but keep the vessel sealed and labelled'],
      ['Plant roots in a growth medium', 'Rhizodeposition feeding a fuel cell', 'Very low continuous power plus living soil chemistry', 'Hours', 'Growing season', 'Plant pot as the power module', '3', 'No hazard; avoid invasive species outdoors'],
      ['Muscle-cell biohybrid actuator', 'Cardiac or skeletal myocytes on an elastic scaffold', 'Millimetre-scale walking and gripping at low force', 'Hundreds of milliseconds', 'Days to weeks in vitro', 'Requires incubator, culture media and pH/temperature control', '2–3', 'Animal-derived cells; institutional ethics approval required, not a home project'],
      ['Physarum polycephalum', 'Slime mould foraging', 'Network optimisation, path finding, simple logic gates', 'Hours', 'Days', 'Oat flakes on agar; results read optically', '3–4', 'Non-pathogenic, but plates must be autoclaved after use'],
      ['Bioluminescent bacteria', 'Aliivibrio fischeri quorum sensing, lux operon', 'Motion- or density-linked light output', 'Hours to become visible', 'Days', 'Sealed bioreactor on a robot, photodiode or TSL2591 readout', '2–3', 'Containment, sterilisation of waste, no plasmid work or resistance markers at home'],
      ['Spider silk and silk fibroin', 'Bombyx mori or recombinant silk', 'High-toughness fibres and films for tendons and implants', 'n/a (material)', 'Years', 'Weaving, lamination, wet spinning', '4–6', 'Animal welfare in farming; recombinant routes avoid it'],
      ['Diatom / algae biofilm', 'Photosynthetic microalgae', 'Oxygen and biomass production, optical density sensing', 'Minutes to hours', 'Weeks', 'Photobioreactor with light and CO2', '3–4', 'Sealed vessel, avoid eutrophication if released'],
    ],
    insight:
      'The engineering question for a living component is not "is it clever" but "how do I measure it, how do I stop it, and how do I dispose of it". Answer those three and living materials become design choices rather than novelties.',
  },
  {
    id: 'frontier-tech',
    title: 'Frontier technologies: hype versus reality',
    category: 'frontier',
    intro:
      'Apply one test to any frontier claim: what is the measured number, what is the method, and what would break if the claim were false? No number means it is a story.',
    columns: ['Technology', 'Principle', 'Maturity (TRL)', 'Real performance today', 'Hype versus reality', 'Robotics relevance'],
    rows: [
      ['NV-centre magnetometry', 'Spin-dependent fluorescence in diamond vacancies', '4–6', '~nT/√Hz sensitivity at room temperature; ODMR around 2.87 GHz', 'Real and remarkable; still needs microwave drive, shielding and optical alignment', 'GPS-denied navigation, subsurface and buried-object mapping'],
      ['Optical atomic clock', 'Narrow optical transitions in trapped atoms/ions', '6–8 in labs', 'Fractional stability approaching 1e-18 in the best lattice clocks', 'Genuinely extraordinary; portable versions are tabletop-scale and expensive', 'Timing, relativity-grade navigation, geodesy'],
      ['Atom interferometer', 'Matter-wave interference in free fall', '4–6', 'Gravimetry to ~1e-9 g in laboratory instruments', 'Works; size, vibration isolation and cost limit field use', 'Gravity mapping, void and tunnel detection'],
      ['SQUID magnetometer', 'Josephson tunnelling', '7–9', 'fT/√Hz sensitivity', 'Mature in medicine and geophysics; requires cryogenics', 'Biomagnetic and geophysical survey (not onboard robots)'],
      ['Quantum LiDAR / radar', 'Entangled or squeezed photon states', '1–3', 'Mostly theoretical or modest quantum-enhanced sensing in the lab', 'Strong claims, weak demonstrated field advantage over classical sensors', 'Possible niche advantage; treat procurement claims sceptically'],
      ['Superconducting qubit', 'Josephson junctions, microwave control', '3–5', 'Tens to hundreds of physical qubits; two-qubit gate errors around 1e-3', 'Real hardware, far from fault tolerance; needs millikelvin cooling', 'Long-horizon optimisation; not a robot controller'],
      ['Trapped ion qubit', 'Laser-controlled ion hyperfine states', '3–5', 'Very high gate fidelity (~1e-3 or better), slow gates', 'Excellent fidelity, poor speed and scaling', 'Same as above'],
      ['Photonic quantum computing', 'Linear optics and single-photon sources', '2–4', 'Small-scale demonstrations, room temperature', 'Big promises, hard photon-loss problem', 'Long-horizon'],
      ['Quantum annealing', 'Adiabatic evolution of an Ising Hamiltonian', '4–6', 'Thousands of qubits, useful for some QUBO problems', 'Real machines, contested speedups versus classical heuristics', 'Fleet task allocation experiments'],
      ['Post-quantum cryptography', 'Lattice-based KEMs and signatures (ML-KEM, ML-DSA)', '7–9 (deployable now)', 'Standardised and running in production stacks', 'Under-hyped: it is a scheduled migration, not a research project', 'Every connected fleet with a multi-year service life'],
      ['Neuromorphic hardware', 'Event-driven spiking computation', '4–6', 'Microwatt-class inference on sparse event data (e.g. Loihi 2)', 'Real energy wins on the right workload; tooling still immature', 'Always-on wake-up perception, anomaly detection'],
      ['Memristor / RRAM in-memory compute', 'Resistive switching for analog multiply-accumulate', '3–5', 'Lab demonstrations of matrix operations at low energy', 'Promising; endurance and variability unresolved', 'Edge inference in a few years'],
      ['Photonic computing', 'Optical matrix multiplication and interconnects', '3–5', 'Optical interconnects are shipping; optical compute is early', 'Interconnect is real, compute is mostly demonstration', 'High-bandwidth sensor and datacentre links'],
      ['Spiking neural networks', 'Temporal spike coding', '3–5', 'Competitive accuracy on event-camera tasks', 'Efficient for event data, awkward for everything else', 'Event-camera perception on low-power robots'],
      ['Powered exoskeleton', 'Series elastic or hydraulic actuation of a worn frame', '6–8', 'Industrial and medical devices in real use; full-body suits need kW', 'Real in rehabilitation and lifting niches, heavy and costly in general', 'Assistive work, rehab, load carriage'],
      ['Neural interface (EMG / implanted)', 'Myoelectric or intracortical recording', '5–9 depending on invasiveness', 'Commercial myoelectric hands; intracortical control demonstrated in trials', 'Myoelectric is commodity; implanted arrays remain clinical', 'Prosthetics, assistive robotics'],
    ],
    insight:
      'Sort frontier technology into three bins: usable now (post-quantum crypto, NV sensing in a lab, event cameras), usable soon with a named blocker (neuromorphic tooling, portable optical clocks), and narrative only (most quantum-computing-for-robotics claims). Say which bin a claim is in, and the conversation becomes engineering.',
  },
  {
    id: 'safety-standards',
    title: 'Safety standards map',
    category: 'frontier',
    intro:
      'You do not need clause numbers memorised. You need to know which standard governs your product, what evidence it demands, and that the evidence is measurement on the actual machine.',
    columns: ['Standard', 'Scope', 'Region', 'Key requirement', 'Applies to', 'What you must produce'],
    rows: [
      ['ISO 12100', 'Risk assessment methodology', 'International', 'Hazard identification and the three-step reduction hierarchy', 'Every machine', 'Risk assessment file with residual risks listed'],
      ['ISO 10218-1', 'Industrial robot safety (the robot)', 'International', 'Safety-rated functions, e-stop, limiting spaces, verification', 'Robot manufacturers', 'Design validation and functional test records'],
      ['ISO 10218-2', 'Industrial robot safety (the cell)', 'International', 'Integration requirements, safeguarding, layout', 'System integrators', 'Cell layout review, guarding design, verification'],
      ['ISO/TS 15066', 'Collaborative robot operation', 'International', 'Four collaboration modes plus biomechanical force and pressure limits', 'Cobot cells', 'Force and pressure measurements at contact points'],
      ['ISO 13849-1', 'Safety-related control systems', 'International', 'Performance level PL a–e from category, MTTFd, diagnostic coverage, CCF', 'Safety functions', 'PL calculation per safety function'],
      ['IEC 61508', 'Functional safety (generic)', 'International', 'SIL 1–4 with hardware fault tolerance and systematic capability', 'Electrical/electronic safety systems', 'Safety requirements specification and verification'],
      ['IEC 62061', 'Functional safety for machinery', 'International', 'SIL for machine safety functions', 'Machinery control', 'SIL allocation and validation records'],
      ['IEC 60204-1', 'Electrical equipment of machines', 'International', 'Stop categories 0/1/2, emergency stop as complementary protection, wiring practice', 'Power and control systems', 'Stop category declaration, wiring diagrams, testing'],
      ['ISO 3691-4', 'Driverless industrial trucks (AMR/AGV)', 'International', 'Speed, braking, personnel detection, clearance', 'Mobile robots', 'Braking distance test on the actual floor surface'],
      ['ANSI/RIA R15.08', 'Industrial mobile robots', 'United States', 'Part 1 robot, part 2 integrator, part 3 user requirements', 'Mobile robot deployments', 'Compliance documentation per part'],
      ['ISO 9283', 'Manipulator performance criteria', 'International', 'Defined pose accuracy, repeatability and path tests', 'Manipulators', 'Measurement protocol and results'],
      ['ISO 13482', 'Personal care robots', 'International', 'Safety for mobile servant, physical assistant and person carrier robots', 'Service and care robots', 'Hazard analysis specific to human contact'],
      ['ISO 21448 (SOTIF)', 'Safety of the intended functionality', 'International', 'Handle performance limitations and triggering conditions, not just failures', 'Autonomous and AI functions', 'Scenario analysis and residual risk argument'],
      ['UL 4600', 'Autonomous products', 'United States', 'Structured safety case: claims, arguments, evidence', 'Fully autonomous systems', 'A written safety case, not just a test report'],
      ['FAA Part 107', 'Small unmanned aircraft operations', 'United States', 'Registration, remote pilot certificate, altitude and airspace limits, VLOS', 'Drone operations', 'Flight records, airspace authorisation, waivers'],
      ['EASA UAS rules (open/specific/certified)', 'Drone operations by risk category', 'European Union', 'Category-dependent limits, operator registration, remote ID', 'Drone operations', 'Operational risk assessment and authorisation'],
    ],
    insight:
      'Standards are evidence specifications, not paperwork. If you cannot point at a measurement, a calculation or a documented test for a claim, the standard is telling you the claim is not yet supported.',
  },
  {
    id: 'afro-technical-heritage',
    title: 'Afro-technical heritage and what a roboticist should take from it',
    category: 'frontier',
    intro:
      'A working inventory of documented and archaeological achievements, with the genuine engineering idea inside each and an honest epistemic status. Contested claims are labelled as such rather than resolved in the course favour.',
    columns: ['Achievement', 'Culture / region', 'Approx. date', 'What it is', 'Engineering idea worth stealing', 'Status'],
    rows: [
      ['Ishango bone', 'Congo basin (DRC)', '~20,000 years ago', 'Baboon fibula with grouped tally notches', 'Abstracting a continuous process into countable discrete states — the origin of the sample', 'Archaeological; lunar-calendar reading is debated'],
      ['Lebombo bone', 'Eswatini / South Africa', '~35,000–44,000 years ago', 'Baboon fibula with 29 notches', 'Recording cycles rather than moments', 'Archaeological; lunar interpretation is disputed'],
      ['Nabta Playa', 'Egypt (Western Desert)', '~7,000 years ago', 'Megalithic alignments and a calendar circle', 'Aligning infrastructure to an external reference to avoid cumulative drift', 'Archaeological'],
      ['Kemetic water clock (clepsydra)', 'Kemet (Egypt)', '~3,400 years ago', 'Outflow vessel with decan markings; Karnak example of Amenhotep III', 'A calibrated model of a nonlinear process: the water level is read against a scale that compensates for falling head', 'Documented'],
      ['Shaduf and basin irrigation', 'Kemet (Egypt)', '~3,500 years ago', 'Counterweighted lever for lifting water; Nile flood basin management', 'Mechanical advantage for repetitive work, and centralised scheduling of a shared resource', 'Documented and still in use'],
      ['Kemetic temple door and statue mechanisms', 'Kemet (Egypt)', '~2,200 years ago', 'Accounts of doors and figures moved by hidden mechanisms, air or water', 'Concealing the mechanism to produce a designed effect on the observer', 'Mixed: some documented, some later literary accounts'],
      ['Nok terracotta and early iron', 'Nigeria (Jos Plateau)', '~1500 BCE–500 CE', 'Large-scale terracotta sculpture plus West African iron smelting', 'Independent invention of high-temperature pyrotechnology and controlled furnace atmospheres', 'Archaeological'],
      ['Haya steel furnaces', 'Tanzania (Kagera)', 'c. 1500–2000 CE', 'Pre-industrial furnaces producing high-carbon steel, with preheated air', 'Preheating combustion air to reach 1500–2000 °C with simple materials — a heat-recovery loop', 'Documented and archaeologically reconstructed'],
      ['Meroitic iron production', 'Kush / Nubia (Sudan)', 'c. 500 BCE–350 CE', 'Industrial-scale smelting with extensive slag mounds at Meroe', 'Production at scale: furnace batteries, fuel logistics and waste management as a system', 'Archaeological'],
      ['Aksumite stelae', 'Ethiopia (Aksum)', 'c. 300–500 CE', 'Quarried, transported and erected granite obelisks of hundreds of tonnes', 'Logistics engineering: moving and standing a mass far larger than any single tool', 'Archaeological'],
      ['Rock-hewn churches of Lalibela', 'Ethiopia', 'c. 12th–13th century', 'Monolithic churches carved downward into volcanic rock', 'Subtractive manufacturing: design the process so the structure emerges from the removal sequence', 'Documented; still in use'],
      ['Great Zimbabwe dry-stone walling', 'Zimbabwe', 'c. 11th–15th century', 'Curved, mortarless granite walls using stacked stone', 'Implicit force paths: stability from geometry and friction rather than adhesive bond', 'Archaeological'],
      ['Timbuktu manuscripts and Sankore', 'Mali', '13th–16th century', 'Hundreds of thousands of manuscripts on astronomy, maths, medicine, law', 'Systematic notation and replication: knowledge engineering as durable infrastructure', 'Documented'],
      ['Djenné Great Mosque and banco building', 'Mali', '13th century, rebuilt 1907', 'Large mud-brick structure with toron buttresses and annual re-plastering', 'Planned maintenance culture: a material that only works if the upkeep cycle is a design feature', 'Documented and in use'],
      ['Ifá divination system', 'Yoruba (Nigeria, Benin)', 'Living tradition, centuries old', '16 principal odù combining to 256 configurations, with an extensive oral corpus', 'A combinatorial knowledge base indexed by a compact code — decision support with structured retrieval', 'Living tradition; binary-coding description is debated'],
      ['Adinkra symbols', 'Akan (Ghana, Côte d Ivoire)', '19th century onward', 'A visual symbol system encoding proverbs, values and observations', 'Compact, learnable symbolic encoding of complex semantic states — a human-facing status language', 'Documented and in use'],
      ['Kente cloth structure', 'Asante and Ewe (Ghana, Togo)', 'c. 17th century onward', 'Narrow-strip weaving assembled into patterned cloth with named motifs', 'Hierarchical composition: local rule-governed units combined into a global pattern with meaning', 'Living tradition'],
      ['Ron Eglash African fractals', 'Pan-African (architecture, textiles, hairstyling, divination)', 'Documented from the 1980s onward', 'Self-similar scaling and recursion in design practice', 'Recursion and scaling as design grammar — the same idea behind recursive structures and fractal antennas', 'Documented scholarship'],
      ['Termite-mound ventilation and Eastgate Centre', 'Zimbabwe (mound study) and Harare (building, 1996)', 'Building completed 1996', 'Passive stack ventilation inspired by mound thermal regulation', 'Using a small pressure differential and thermal mass instead of powered cooling', 'Documented; the direct causal link between mound and building is often overstated'],
      ['Dogon astronomy and Sirius', 'Mali (Dogon country)', 'Ethnography from the 1930s–1950s', 'Sirius and its companion feature in Dogon cosmology and the sigi ceremony', 'Star-based calendrical reckoning as long-baseline timekeeping', 'Disputed: the Sirius B claims (Griaule/Temple) are contested by anthropologists'],
      ['Afrofuturism', 'Pan-African diaspora', '1990s onward, roots in the 1950s–70s', 'Cultural movement fusing African diaspora experience with technology and speculative futures', 'Design fiction as an engineering tool: imagine the user before imagining the device', 'Documented cultural movement'],
      ['Wakanda production design', 'Global African diaspora creative labour', '2018 onward', 'Ruth E. Carter costume design and Hannah Beachler sets fusing Maasai, Surma, Tuareg, kente, Adinkra and other influences', 'Material storytelling: heterogeneous traditions combined coherently into one visual system', 'Documented; vibranium is fictional'],
    ],
    insight:
      'The reason to teach this table is not pride, it is design range. Mortarless walls, preheated furnaces, combinatorial divination codes and passive stack ventilation are all solutions to problems engineers still solve badly — and they were solved with less energy, fewer materials and better maintenance thinking than most modern equivalents.',
  },
];
