import type { Lesson } from '../types';

export const lesson: Lesson = {
  id: 'w2l4',
  number: 4,
  week: 2,
  track: 'perception',
  title: 'Exteroception and Machine Vision: From Ultrasonic to LiDAR',
  subtitle: 'Every sense has a failure mode — pick yours deliberately',
  duration: 70,
  difficulty: 'apprentice',
  xp: 175,
  hook: 'A sensor is not a window on the world. It is a contract with a failure mode written in the fine print.',
  objectives: [
    'Compute range from ultrasonic time of flight and state the beam-angle and surface conditions that break it.',
    'Tell dToF from iToF and place VL53L0X, VL53L1X and TF-Luna on real ranges with units.',
    'Compare pulsed ToF, AMCW and triangulation LiDAR, including 905 nm vs 1550 nm eye-safety classes.',
    'Derive stereo depth error z²/(f·B) and predict when stereo fails but radar holds.',
    'Calibrate intrinsics, extrinsics and distortion from a checkerboard, then read a point cloud correctly.',
  ],
  blocks: [
    { kind: 'prose', heading: 'Sound is slow, and that is the whole budget',
      body: 'An ultrasonic ranger fires a 40 kHz burst, waits for the echo, and reports $z = c\\,t/2$. At 20 °C sound travels at **343 m/s**, so 1 ms of round trip is 171.5 mm of range and the 58 kHz-capable HC-SR04 must wait ~24 ms for a 4 m echo. That caps it near **25-40 readings per second**, and any second echo arriving later is simply lost.\n\n' +
        'The transducer is a piston, not a laser: the HC-SR04 spreads roughly **15°** either side of boresight, so at 3 m the footprint is about **1.6 m wide** — it reports the *nearest* thing in that cone. Soft foam at 40 kHz absorbs instead of reflecting; a small pole inside the cone returns almost nothing. Worse, the sensor is deaf while transmitting, so anything closer than ~20 cm is blind.' },
    { kind: 'formula', title: 'Time of flight and the speed-of-sound correction',
      tex: 'z = \\frac{c\\,t}{2}, \\qquad c \\approx 331.3 + 0.606\\,T\\ [\\mathrm{m/s}]',
      explain: 'Range is half the round-trip time because the pulse travels out and back. c rises 0.606 m/s per °C: a 0 °C room makes every 3 m reading 3.5% short unless you correct it.' },
    { kind: 'callout', tone: 'warning', title: 'The three surfaces that blind half your sensors',
      body: '**Specular**: a mirror, wet floor or gloss-painted wall sends the beam away from the receiver — LiDAR drops the return entirely. **Dark**: matte black felt has ~2-5% diffuse reflectance, so at 10 m a 905 nm LiDAR sees 1/20 of the photons a white wall gives and SNR collapses. **Transparent**: glass reflects ~4% at normal incidence and passes the rest, so time of flight measures the wall *behind* it while structured light and stereo may see nothing at all. Every one of these defeats ultrasonic, IR, ToF, LiDAR and stereo in a different order — which is exactly why you fuse.' },
    { kind: 'table', title: 'Exteroceptive sensors, datasheet numbers',
      caption: 'All figures are typical datasheet values at 20-25 °C; "cost" is single-unit 2024 hobbyist pricing.',
      columns: ['Sensor', 'Principle', 'Range', 'Update rate', 'Beam', 'Killer failure mode'],
      rows: [
        ['HC-SR04', 'Ultrasonic 40 kHz', '0.02-4 m, ±3 mm', '~25-40 Hz', '~15°', 'Soft/absorbent targets; c drifts 0.18%/°C'],
        ['Sharp GP2Y0A21', 'IR triangulation', '0.10-0.80 m', '~30 Hz (analog)', '~5°', 'Nonlinear 1/z curve; sunlight and dark surfaces'],
        ['VL53L0X', 'dToF 940 nm SPAD', '0.03-2 m', 'up to 50 Hz', '25°', 'Ambient IR; 2 m ceiling'],
        ['VL53L1X', 'dToF + adjustable FoV', '0.04-4 m', 'up to 60 Hz', '15-27°', 'Sunlight at long range; cover glass crosstalk'],
        ['TF-Luna', 'dToF 850 nm', '0.2-8 m, ±6 cm', '100-250 Hz', '~2°', 'Only a single point; 100 klx daylight'],
        ['RPLIDAR A1', 'Spinning pulsed ToF 785 nm', '0.15-12 m', '5.5 Hz scan (2 kHz)', '1° steps', 'Strong sunlight, glass, black fabric'],
        ['RPLIDAR A2', 'Spinning pulsed ToF 785 nm', '0.2-16 m', '10 Hz scan (4 kHz)', '0.9°', 'Same optical failures; moving parts wear'],
        ['TI IWR6843', 'FMCW radar 60-64 GHz', '0.2-15 m (people)', '20-30 Hz frames', '±60° azimuth', 'Poor angular resolution (~15°); metallic clutter'],
      ] },
    { kind: 'prose', heading: 'dToF, iToF and the IR sensor you should stop using',
      body: 'A **Sharp GP2Y0A21** is IR triangulation: an emitter and a linear CCD a fixed baseline apart, so range is where the spot lands. Output is a steeply nonlinear 1/z voltage (about 3.1 V at 10 cm, 0.4 V at 80 cm), and it moves with target reflectance and indoor sunlight — fine for a 15 cm cliff reflex, useless as a range measurement.\n\n' +
        '**Indirect ToF (iToF)** — ST VL53L0X and VL53L1X — modulates a 940 nm emitter and measures the *phase* of the returning light. Short pulses mean low peak power, but phase wraps past one modulation period and multipath inside a corridor biases the result. **Direct ToF (dToF)** times individual photons with a SPAD: the TF-Luna (850 nm) reaches **8 m at ±6 cm** and up to 250 Hz, which is what makes 1D dToF the workhorse of drone altitude hold. The VL53L0X is the cheap 2 m part; the VL53L1X adds a programmable region of interest that shrinks the field of view to 15° when you need to shoot between chair legs.' },
    { kind: 'prose', heading: 'LiDAR: three ways to measure a photon, two wavelengths, three ways to steer',
      body: '**Pulsed ToF** fires a nanosecond-class 905 nm pulse and times it (RPLIDAR A2, Velodyne, Ouster). It is unambiguous over hundreds of metres. **AMCW** modulates a continuous beam and measures phase like iToF — accurate but ambiguous, now mostly historical. **Triangulation** LiDAR (original Neato XV-11) reads a spot on a CMOS line and dies past ~6 m as the baseline geometry closes.\n\n' +
        '**905 nm** silicon detectors are cheap and efficient, but that light focuses onto the retina, so IEC 60825-1 Class 1 caps average power near **~0.2-0.3 mW** for typical pulse trains — enough for 100-300 m at low scan rates. **1550 nm** is absorbed by water in the cornea and lens before it reaches the retina, so Class 1 allows roughly **20× to 100×** more power (Luminar, Aeva), buying longer range or higher scan rate at several times the cost. That is a safety-standard trade, not a marketing one: both are Class 1 as shipped.\n\n' +
        'Steering is the other axis. **Spinning** assemblies (RPLIDAR A1 at ~2 kHz, A2 at ~4 kHz, 360°) are proven and have bearings. **Solid-state MEMS** mirrors scan a few tens of degrees with no spinning mass but must be stitched together. **OPA** steers with no moving parts at all and is still largely in the lab. For most builds the honest answer in 2024 is still a spinning unit plus a camera.' },
    { kind: 'prose', heading: 'Radar: worse angles, better physics',
      body: 'FMCW radar sweeps 24, 60 or 77 GHz and mixes the echo with the transmitted chirp. The beat frequency gives range, and because the target is moving the return is shifted in frequency by the **Doppler** term, so one frame gives range *and* radial velocity per detection. The TI IWR6843 (60-64 GHz, 3 TX / 4 RX) resolves people to ~15 cm in range but only ~15° in angle, and it penetrates fog, dust, rain and plastic enclosures that stop every optical sensor — 77 GHz attenuates ~1-2 dB/km in heavy rain. Use radar for velocity and all-weather presence, not for shape.' },
    { kind: 'formula', title: 'Stereo depth uncertainty scales as z²',
      tex: 'z = \\frac{f\\,B}{d}, \\qquad \\frac{\\partial z}{\\partial d} = -\\frac{z^{2}}{f\\,B}\\;\\Rightarrow\\; \\sigma_z \\approx \\frac{z^{2}}{f\\,B}\\,\\sigma_d',
      explain: 'Disparity d (pixels) turns into depth z for focal length f and baseline B. Error grows with the square of distance, so stereo is a close-range sensor by nature.' },
    { kind: 'chart', title: 'Stereo depth error at f = 350 px, B = 60 mm',
      caption: 'Assumes 0.25 px disparity noise (subpixel block matching). Radar loses angular resolution where stereo loses depth.',
      chartType: 'line', xLabel: 'Range z (m)', yLabel: 'Depth error σz (m)',
      x: [1, 2, 3, 5, 8, 12, 16],
      series: [{ key: 'sz', label: 'Stereo σz at σd = 0.25 px', color: '#22d3ee', data: [0.002, 0.010, 0.021, 0.060, 0.152, 0.343, 0.610] }] },
    { kind: 'code', title: 'Pinhole projection and back-projection', language: 'python',
      note: 'Run without numpy: this is the arithmetic a driver performs. Distortion and extrinsics are the next two matrices in the chain.',
      code: 'fx, fy, cx, cy = 615.0, 615.0, 320.0, 240.0   # 640x480, ~60 deg HFOV\n' +
        'X, Y, Z = 0.30, -0.10, 2.0                      # metres, camera frame\n\n' +
        'u = fx * X / Z + cx      # 412.25 px\n' +
        'v = fy * Y / Z + cy      # 209.25 px\n' +
        'print("u,v =", round(u, 2), round(v, 2))\n\n' +
        '# invert: recover the ray from a pixel at measured depth\n' +
        'u, v, Z = 412.25, 209.25, 2.0\n' +
        'X = (u - cx) * Z / fx    # 0.30 m\n' +
        'Y = (v - cy) * Z / fy    # -0.10 m\n' +
        'print("X,Y =", round(X, 3), round(Y, 3))' },
    { kind: 'lab', labId: 'vision-grid', title: 'Build a depth map you can trust',
      brief: 'Render a scene through a pinhole camera with configurable baseline, focal length and a simulated failure surface.',
      tasks: ['Set B = 60 mm and f = 350 px, then measure depth error at 1, 4 and 12 m and compare with z²/(f·B).', 'Replace the matte wall with a specular panel and black felt; log which sensor returns garbage on each.', 'Calibrate the virtual camera from 12 checkerboard views and report residual reprojection error in pixels.'] },
    { kind: 'lab', labId: 'kalman', title: 'Fuse the senses, weight the failure',
      brief: 'Drive one state estimate from noisy ultrasonic, ToF and vision measurements with per-sensor dropout modelling.',
      tasks: ['Fuse 343 m/s ultrasonic at 30 Hz with 100 Hz dToF and report whether the estimate beats dToF alone.', 'Drop 40% of the vision updates during the dark-fabric phase and watch the covariance grow.', 'Inject a 1-2 cm ultrasonic bias from 30 °C air and show whether fusion hides or amplifies it.'] },
    { kind: 'steps', title: 'From photons to a labelled point cloud',
      steps: [
        { title: 'Calibrate intrinsics', detail: 'Wave a 9x6-inner-corner checkerboard through 15-20 views; solve for fx, fy, cx, cy and the 5 distortion terms, then check residual error is under ~0.3 px.' },
        { title: 'Fix extrinsics', detail: 'Find the rigid transform between camera and LiDAR from a target visible in both; a 1° rotation error is 17 mm of misalignment at 1 m.' },
        { title: 'Rectify and undistort', detail: 'Remap the image so epipolar lines are horizontal; this is what makes stereo matching a 1D search.' },
        { title: 'Build the point cloud', detail: 'Back-project each pixel with its depth, transform into the base frame, and keep the noise units honest (mm, not "good").' },
        { title: 'Detect and segment', detail: 'YOLO gives boxes at 30-100 FPS on a Jetson Orin Nano; Mask R-CNN gives masks at a few FPS; SAM segments anything but needs a prompt and heavy compute.' },
        { title: 'Check the clock', detail: 'A rolling shutter reads a 640x480 frame over ~30 ms: at 1 m/s that skews the image by ~30 mm, which silently breaks projection into the LiDAR frame.' },
      ] },
    { kind: 'prose', heading: 'What actually runs on the edge',
      body: 'A **Jetson Orin Nano** (8 GB, 40 TOPS dense INT8, 7-15 W) runs YOLOv8n/s at roughly 30-70 FPS and a light segmentation net at 10-20 FPS; a **Google Coral Edge TPU** (4 TOPS INT8, ~2 W) runs quantized MobileNet/YOLO at 30+ FPS but refuses unsupported ops. Mask R-CNN is a two-stage network: masks at 2-10 FPS on the same Orin. **SAM** needs a prompt — points, boxes or a mask — and its smallest ViT-B checkpoint wants seconds per image on an Orin, so in 2024 it is a labelling or cloud tool, not an onboard detector. Onboard trade: quantize, shrink the input to 320 or 416 px, and accept the recall you actually measured rather than the number from the paper.' },
  ],
  keyTerms: [
    { term: 'Exteroception', definition: 'Sensing the world outside the body: range, light, sound, radio — as opposed to proprioception.' },
    { term: 'Time of flight (ToF)', definition: 'Range from travel time: z = c·t/2 for sound and light alike, with c differing by ~880,000×.' },
    { term: 'dToF vs iToF', definition: 'Direct ToF times individual photon returns (TF-Luna); indirect ToF measures the phase of a modulated beam (VL53L1X) and can wrap.' },
    { term: 'Specular reflection', definition: 'A mirror-like bounce that sends the beam away from the receiver, producing a false "no return".' },
    { term: 'FMCW radar', definition: 'Frequency-modulated continuous wave: beat frequency gives range, Doppler shift gives radial velocity in the same chirp.' },
    { term: 'Stereo disparity', definition: 'Horizontal pixel shift d between matched features; depth is z = f·B/d and error grows as z².' },
    { term: 'Intrinsics and extrinsics', definition: 'Intrinsics: fx, fy, cx, cy and distortion. Extrinsics: the rigid transform between sensor and robot frames.' },
    { term: 'Rolling shutter', definition: 'Row-by-row exposure over ~30 ms that skews moving objects and breaks time alignment with other sensors.' },
  ],
  quiz: [
    { id: 'w2l4q1', question: 'An ultrasonic sensor at 20 °C measures a 17.2 ms round trip. What is the range?',
      choices: ['2.95 m', '1.47 m', '5.90 m', '8.60 m'], answer: 0, level: 'apply',
      explanation: 'z = c·t/2 = 343 × 0.0172 / 2 = 2.95 m. Forgetting the factor of 2 doubles it to 5.90 m.' },
    { id: 'w2l4q2', question: 'A LiDAR scan shows a clean wall except for a 40 cm hole exactly where the corridor glass is. The most likely cause is...',
      choices: ['the glass is too dark to reflect', 'the glass passes and specularly reflects the beam away from the receiver', 'the laser is out of eye-safety class', 'the glass is beyond the 12 m range'], answer: 1, level: 'analyze',
      explanation: 'Clear glass reflects only ~4% at normal incidence and sends the specular lobe off-axis; the receiver sees nothing, so the point is dropped.' },
    { id: 'w2l4q3', question: 'Which pairing of principle and example is correct?',
      choices: ['AMCW: RPLIDAR A2', 'Triangulation: TF-Luna', 'Direct ToF: VL53L1X', 'Indirect ToF: VL53L0X'], answer: 3, level: 'recall',
      explanation: 'VL53L0X and VL53L1X are phase-based iToF. RPLIDAR A2 is pulsed ToF, TF-Luna is dToF, and triangulation is the old Neato XV-11 style.' },
    { id: 'w2l4q4', question: 'A 1550 nm LiDAR may emit far more average power than a 905 nm unit at the same IEC 60825-1 class because...',
      choices: ['1550 nm photons carry less energy', 'water in the cornea and lens absorbs 1550 nm before it reaches the retina', '1550 nm is invisible so it is exempt', 'class limits scale with wavelength squared'], answer: 1, level: 'understand',
      explanation: 'Ocular absorption at 1550 nm keeps the light off the retina, so the Class 1 accessible-emission limit is roughly 20-100× higher than at 905 nm.' },
    { id: 'w2l4q5', question: 'A stereo rig has f = 350 px, B = 60 mm and 0.25 px disparity noise. Depth error at 12 m is about...',
      choices: ['0.09 m', '0.34 m', '1.20 m', '3.40 m'], answer: 1, level: 'apply',
      explanation: 'σz ≈ z²σd/(f·B) = 144 × 0.25 / (350 × 0.06) = 0.343 m. Error quadruples every time range doubles.' },
    { id: 'w2l4q6', question: 'At 4 m you must detect a pedestrian in fog and rain and report closing speed. Which sensor carries that job?',
      choices: ['905 nm spinning LiDAR', 'VL53L1X dToF', '60 GHz FMCW radar (IWR6843)', 'rolling-shutter camera with YOLOv8'], answer: 2, level: 'design',
      explanation: 'FMCW radar penetrates fog and rain with only ~1-2 dB/km loss and gives radial velocity from Doppler; its weak angular resolution is the price.' },
    { id: 'w2l4q7', question: 'You need "segment anything" on a 15 W Orin Nano at 20 FPS. What is the honest conclusion?',
      choices: ['SAM ViT-B runs at 20 FPS after INT8 quantization', 'SAM needs a prompt and heavy compute, so use a small YOLO detector or a distilled segmenter instead', 'Mask R-CNN is the lightest option at 30 FPS', 'Coral Edge TPU runs SAM natively at 4 TOPS'], answer: 1, level: 'design',
      explanation: 'SAM is prompt-based and its smallest checkpoint needs seconds per image on an Orin; YOLO-class or distilled segmenters are what fit a 15 W budget.' },
  ],
  flashcards: [
    { front: 'Speed of sound at 20 °C', back: '343 m/s; about 0.606 m/s faster per °C, so range reads 3.5% short at 0 °C unless corrected.', tag: 'ultrasonic' },
    { front: 'Ultrasonic beam angle', back: 'HC-SR04 spreads ~15° per side — a ~1.6 m footprint at 3 m, reporting the nearest object in the cone.', tag: 'ultrasonic' },
    { front: 'IR proximity nonlinearity', back: 'GP2Y0A21 outputs ~3.1 V at 10 cm and ~0.4 V at 80 cm; the 1/z curve also shifts with reflectance and sunlight.', tag: 'ir' },
    { front: 'iToF vs dToF', back: 'iToF measures modulation phase (VL53L0X/L1X, wraps, multipath-biased); dToF times photons (TF-Luna, 8 m, 250 Hz).', tag: 'tof' },
    { front: 'LiDAR architectures', back: 'Pulsed ToF (long range), AMCW (phase, ambiguous), triangulation (short range, geometry-limited).', tag: 'lidar' },
    { front: '905 vs 1550 nm', back: '905 nm focuses on the retina, capping Class 1 near 0.2-0.3 mW; 1550 nm is absorbed by the eye, allowing 20-100× more.', tag: 'lidar' },
    { front: 'FMCW radar', back: 'Beat frequency gives range, Doppler gives radial velocity; TI IWR6843 at 60-64 GHz, ~15 cm range and ~15° angular resolution.', tag: 'radar' },
    { front: 'Stereo error law', back: 'σz ≈ z²σd/(f·B): at f = 350 px, B = 60 mm, σd = 0.25 px the error is 2 mm at 1 m and 0.61 m at 16 m.', tag: 'stereo' },
    { front: 'Rolling shutter skew', back: 'A 640x480 frame exposed over ~30 ms shifts a 1 m/s target by ~30 mm and breaks camera-LiDAR time alignment.', tag: 'camera' },
    { front: 'Edge segmentation', back: 'Orin Nano: YOLO 30-70 FPS, Mask R-CNN 2-10 FPS, SAM seconds per image and needs prompts — not an onboard detector.', tag: 'compute' },
  ],
  forgePrompts: [
    'Build a 3-sensor failure rack — glass, black felt and foam — then log every sensor that lies about each surface.',
    'Fuse 30 Hz ultrasonic with 250 Hz dToF in the Kalman lab and find the air temperature at which the ultrasonic bias poisons the estimate.',
    'Mount a 60 GHz radar next to a camera and learn where the radar is right about motion and the camera is right about shape.',
  ],
};
