import type { Lesson } from '../types';

export const lesson: Lesson = {
  id: 'w4l7',
  number: 7,
  week: 4,
  track: 'kinematics',
  title: 'Kinematics I: Frames, Transforms and Forward Kinematics',
  subtitle: 'Every pose is a chain of multiplications',
  duration: 70,
  difficulty: 'journeyman',
  xp: 185,
  hook: 'A robot arm is a chain of matrix products. Fix the frames and the geometry becomes arithmetic.',
  objectives: [
    'Attach a frame to a body, apply the right-hand rule, and state a pose with 6 numbers.',
    'Test a matrix for SO(3) membership and compose rotations in the correct order.',
    'Explain gimbal lock, then re-express the same attitude as axis-angle and as a unit quaternion.',
    'Build DH tables for a 2-DOF planar and a 6-DOF arm and compute forward kinematics numerically.',
    'Chain transforms from base to TCP, and read the identical chain out of a URDF joint tree.',
  ],
  blocks: [
    { kind: 'prose', heading: 'Frames, poses and the right-hand rule',
      body: 'Three numbers place a point; three more fix its orientation. A **pose** therefore carries **6 degrees of freedom**, and it means nothing until you name the **frame** it is written in: an origin plus three orthonormal axes. The **right-hand rule** settles every sign — $x \\times y = z$, and a positive rotation about an axis appears counter-clockwise when you sight down the $+$axis toward the origin.\n\n' +
        'Write the child axes as the columns of a $3\\times3$ matrix $R$ and you have the orientation. Valid rotations form **SO(3)**: $R^{\\mathsf T}R = I$, so $R^{-1} = R^{\\mathsf T}$, and $\\det R = +1$. A determinant of $-1$ is a mirror, not a rigid motion, and no calibration repairs it. Composition is a product, $R_0^2 = R_0^1 R_1^2$, and matrix multiplication does not commute: rotating about x then y lands somewhere different from y then x. Order is meaning.' },
    { kind: 'formula', title: 'Rotations in 2D and 3D',
      tex: 'R_z(\\theta)=\\begin{bmatrix}c_\\theta & -s_\\theta & 0\\\\ s_\\theta & c_\\theta & 0\\\\ 0 & 0 & 1\\end{bmatrix},\\quad R_y(\\beta)=\\begin{bmatrix}c_\\beta & 0 & s_\\beta\\\\ 0 & 1 & 0\\\\ -s_\\beta & 0 & c_\\beta\\end{bmatrix},\\quad R_x(\\alpha)=\\begin{bmatrix}1 & 0 & 0\\\\ 0 & c_\\alpha & -s_\\alpha\\\\ 0 & s_\\alpha & c_\\alpha\\end{bmatrix},\\quad R = R_z R_y R_x',
      explain: 'Each matrix is a rigid rotation of the vector it multiplies. A 2D rotation is the top-left 2x2 block of Rz. All three satisfy R^T R = I and det R = +1, so every product of them does too.' },
    { kind: 'prose', heading: 'Euler angles, gimbal lock, axis-angle, quaternions',
      body: '**Euler angles** compress an attitude into three numbers, but the packing is a chart choice: 12 conventions exist (proper ZYZ, ZXZ... and Tait-Bryan ZYX, roll-pitch-yaw). **Gimbal lock** hits when the middle angle reaches $\\pm90^\\circ$: in ZYX, $R = R_z(\\gamma)R_y(\\pm90^\\circ)R_x(\\alpha)$ makes the first and third axes act on the same axis, so infinitely many $(\\alpha,\\gamma)$ pairs give one pose. The body still has 3 rotational DOF — the **coordinate chart** lost one. Never divide by $\\cos(\\text{pitch})$ in a controller; store a matrix or quaternion instead.\n\n' +
        '**Axis-angle** names a unit axis $\\hat{n}$ and angle $\\theta$, giving the closed form $R = I + \\sin\\theta\\,[\\hat{n}]_\\times + (1-\\cos\\theta)[\\hat{n}]_\\times^2$ (Rodrigues, 1840). It is global but singular at $\\theta = 0$, where the axis is undefined.\n\n' +
        'A **unit quaternion** $q = (w, x, y, z) = (w, \\mathbf{v})$ obeys $i^2 = j^2 = k^2 = ijk = -1$ and $\\lVert q\\rVert = 1$. Its Hamilton product is $q_1q_2 = (w_1w_2 - \\mathbf{v}_1\\!\\cdot\\!\\mathbf{v}_2,\\; w_1\\mathbf{v}_2 + w_2\\mathbf{v}_1 + \\mathbf{v}_1\\!\\times\\!\\mathbf{v}_2)$, so chains stay products: $q_0^2 = q_0^1 \\otimes q_1^2$. The map is a **double cover** — $q$ and $-q$ are the same rotation, a full $360^\\circ$ turn returns $-q$, and only $720^\\circ$ returns $q$. **Slerp** interpolates on the unit sphere, $q(t) = \\frac{\\sin((1-t)\\Omega)}{\\sin\\Omega}q_0 + \\frac{\\sin t\\Omega}{\\sin\\Omega}q_1$ with $\\Omega = \\arccos(q_0\\!\\cdot\\!q_1)$: constant angular velocity, shortest arc, after flipping a sign whenever $q_0\\!\\cdot\\!q_1 < 0$. Flight controllers at 250 Hz-8 kHz use quaternions because they are 4 numbers with no gimbal lock, compose in 16 multiplies, and renormalise with one square root.' },
    { kind: 'callout', tone: 'warning', title: 'Gimbal lock is a chart problem, not a hardware failure',
      body: 'At pitch $= 90^\\circ$ a three-ring gimbal has its outer and inner rings coplanar: one axis is redundant. Software ZYX Euler angles fail at exactly the same place. The rigid body never lost a single degree of freedom, so fix the representation, not the mechanism — keep attitude as a unit quaternion or rotation matrix and convert to Euler only for the display layer.' },
    { kind: 'table', title: 'DH parameters: 2-DOF planar and 3-DOF anthropomorphic arms',
      caption: 'Classic (distal) DH: a_i and alpha_i describe link i, d_i and theta_i the joint at frame i. The planar arm has alpha = 0 everywhere, so it never leaves the xy-plane; alpha1 = 90 deg lifts the anthropomorphic arm out of the base plane.',
      columns: ['Arm', 'i', 'theta_i', 'd_i (m)', 'a_i (m)', 'alpha_i (deg)'],
      rows: [
        ['2-DOF planar', '1', 'theta1', '0', '0.400', '0'],
        ['2-DOF planar', '2', 'theta2', '0', '0.300', '0'],
        ['3-DOF anthropomorphic', '1', 'theta1', '0.300', '0', '90'],
        ['3-DOF anthropomorphic', '2', 'theta2', '0', '0.400', '0'],
        ['3-DOF anthropomorphic', '3', 'theta3', '0', '0.300', '0'],
      ] },
    { kind: 'table', title: 'DH parameters for a 6-DOF arm (Puma-560 class)',
      caption: 'Rounded to mm. Axes 4, 5 and 6 meet at one point (a4 = a5 = d5 = 0): a spherical wrist, which is what makes closed-form inverse kinematics possible. A sign error in alpha or a moves the tool by centimetres.',
      columns: ['i', 'theta_i', 'd_i (m)', 'a_i (m)', 'alpha_i (deg)'],
      rows: [
        ['1', 'theta1', '0.400', '0', '+90'],
        ['2', 'theta2', '0', '0.432', '0'],
        ['3', 'theta3', '0.150', '0.020', '-90'],
        ['4', 'theta4', '0.432', '0', '+90'],
        ['5', 'theta5', '0', '0', '-90'],
        ['6', 'theta6', '0.056', '0', '0'],
      ] },
    { kind: 'formula', title: 'The DH transform (frame i-1 to frame i)',
      tex: 'A_i = \\mathrm{Rot}_z(\\theta_i)\\,\\mathrm{Trans}_z(d_i)\\,\\mathrm{Trans}_x(a_i)\\,\\mathrm{Rot}_x(\\alpha_i) = \\begin{bmatrix} c_\\theta & -s_\\theta c_\\alpha & s_\\theta s_\\alpha & a c_\\theta \\\\ s_\\theta & c_\\theta c_\\alpha & -c_\\theta s_\\alpha & a s_\\theta \\\\ 0 & s_\\alpha & c_\\alpha & d \\\\ 0 & 0 & 0 & 1 \\end{bmatrix},\\qquad T_0^n = A_1A_2\\cdots A_n',
      explain: 'Each joint contributes 4 numbers. theta is the variable for a revolute joint, d for a prismatic one; a and alpha come from the drawing. The 4x4 form is a homogeneous transform in SE(3): it carries rotation and translation together so chaining is one matrix product.' },
    { kind: 'formula', title: 'Two-link planar forward kinematics',
      tex: 'x = a_1\\cos\\theta_1 + a_2\\cos(\\theta_1+\\theta_2),\\qquad y = a_1\\sin\\theta_1 + a_2\\sin(\\theta_1+\\theta_2)',
      explain: 'Reach is 0.70 m at theta2 = 0 and 0.10 m at theta2 = 180 deg. With a1 = 0.400 m, a2 = 0.300 m, theta1 = 30 deg, theta2 = 45 deg: x = 0.424 m, y = 0.490 m, radius 0.648 m, orientation Rz(75 deg).' },
    { kind: 'chart', title: 'End-effector X/Y traced by the 2-link arm',
      caption: 'a1 = 0.400 m, a2 = 0.300 m, theta2 fixed at 45 deg, theta1 swept 0-180 deg. Sampled every 30 deg; note X is not monotonic — cos(theta1+theta2) eventually wins.',
      chartType: 'line', xLabel: 'Joint 1 angle theta1 (deg), theta2 = 45 deg', yLabel: 'End-effector position (m)',
      x: [0, 30, 60, 90, 120, 150, 180],
      series: [
        { key: 'x', label: 'X (m)', color: '#38bdf8', data: [0.612, 0.424, 0.122, -0.212, -0.490, -0.636, -0.612] },
        { key: 'y', label: 'Y (m)', color: '#f59e0b', data: [0.212, 0.490, 0.636, 0.612, 0.424, 0.122, -0.212] },
      ] },
    { kind: 'code', title: 'Forward kinematics from a DH table', language: 'python',
      note: 'Chaining six DH matrices costs about 100 multiplies. Every inverse-kinematics solver, URDF loader and motion planner sits downstream of this one function.',
      code: `import numpy as np

def dh(a, alpha, d, theta):
    ct, st = np.cos(theta), np.sin(theta)
    ca, sa = np.cos(alpha), np.sin(alpha)
    return np.array([[ct, -st*ca,  st*sa, a*ct],
                     [st,  ct*ca, -ct*sa, a*st],
                     [0,      sa,     ca,    d],
                     [0,       0,      0,    1]])

# 2-DOF planar arm, a1 = 0.400 m, a2 = 0.300 m (alpha = 0)
T = dh(0.400, 0, 0, np.radians(30)) @ dh(0.300, 0, 0, np.radians(45))
print(np.round(T[:3, 3], 3))     # [0.424 0.49  0.   ]
print(np.round(np.degrees(np.arctan2(T[1, 0], T[0, 0])), 1))   # 75.0` },
    { kind: 'steps', title: 'Chain the transforms by hand, then let code repeat it',
      steps: [
        { title: 'Assign frames', detail: 'Put z_i along joint axis i and x_i along the common normal from z_(i-1) to z_i. That fixes 4 numbers per joint: a_i, alpha_i, d_i, theta_i.' },
        { title: 'Write each matrix', detail: 'Substitute into A_i. For a revolute joint theta_i is the variable; a, alpha and d are constants measured from the drawing.' },
        { title: 'Multiply in order', detail: 'T_0^2 = A_1 A_2. Rotations do not commute, so the order encodes which joint sits nearer the base.' },
        { title: 'Read the pose', detail: 'a1 = 0.400 m, a2 = 0.300 m, theta1 = 30 deg, theta2 = 45 deg gives translation (0.424, 0.490, 0) m and orientation Rz(75 deg). Sanity check: radius 0.648 m sits inside the 0.70 m reach.' },
        { title: 'Attach the tool', detail: 'T_0^tool = T_0^6 * T_tool. A 0.120 m gripper offset along z moves the TCP and leaves the wrist flange exactly where it was.' },
        { title: 'Or use the product of exponentials', detail: 'T(theta) = exp([S_1]theta_1) ... exp([S_n]theta_n) M, with space-frame screw axes S_i and home pose M. No frame-assignment bookkeeping, and the same axes a URDF stores.' },
        { title: 'Encode it in URDF', detail: 'Each <joint> carries <origin xyz rpy>, <axis xyz> and its parent/child links. Loaders such as KDL or Pinocchio rebuild precisely the chain above from that XML.' },
      ] },
    { kind: 'lab', labId: 'robot-arm', title: 'Trace the chain',
      brief: 'Drive the 6-DOF arm in the sim and check its forward kinematics against the DH table you just read.',
      tasks: [
        'Set all six joints to zero, read the tool pose, and compare it with T_0^6 from the DH table to within 1 mm.',
        'Set theta2 = 45 deg and sweep theta1 from 0 to 180 deg, then match the plotted tool path to the chart above.',
        'Add a 0.12 m tool offset along z and record how far the TCP moves while the wrist flange stays fixed.',
      ] },
  ],
  keyTerms: [
    { term: 'Frame', definition: 'An origin plus three orthonormal axes; every pose is written relative to one.' },
    { term: 'SO(3)', definition: 'The group of 3x3 rotation matrices: R^T R = I and det R = +1.' },
    { term: 'Homogeneous transform (SE(3))', definition: 'A 4x4 matrix holding rotation and translation together, so chaining is one product.' },
    { term: 'Gimbal lock', definition: 'Loss of one rotational degree of freedom in a coordinate chart when the middle Euler angle is +/-90 deg.' },
    { term: 'Unit quaternion', definition: 'A 4-vector (w, x, y, z) of norm 1 representing a rotation; q and -q are identical.' },
    { term: 'Slerp', definition: 'Interpolation between unit quaternions along the shortest great-circle arc at constant angular velocity.' },
    { term: 'DH parameters', definition: 'Four numbers (a, alpha, d, theta) per joint that fix the transform from link i-1 to link i.' },
    { term: 'TCP', definition: 'Tool centre point: the controlled point at the tool, offset from the wrist flange by a fixed transform.' },
  ],
  quiz: [
    { id: 'w4l7q1', question: 'How many independent numbers define a rigid body pose in 3D space?',
      choices: ['3', '4', '6', '9'], answer: 2, level: 'recall',
      explanation: 'Three for position plus three for orientation. A 3x3 rotation matrix has 9 entries but only 3 independent ones, because R^T R = I removes 6.' },
    { id: 'w4l7q2', question: 'Which pair of properties must a matrix satisfy to be a valid rotation?',
      choices: ['R^T R = I and det R = +1', 'R^T R = 0 and det R = 0', 'R = R^T and det R = -1', 'R^-1 = R and det R = 1'], answer: 0, level: 'understand',
      explanation: 'Orthonormality plus a positive determinant. R^-1 = R holds only for special symmetric cases such as a 180 deg rotation, and det = -1 is a reflection.' },
    { id: 'w4l7q3', question: 'Gimbal lock in ZYX Euler angles occurs when...',
      choices: ['yaw reaches +/-90 deg', 'the middle (pitch) angle reaches +/-90 deg', 'roll and yaw become equal', 'the quaternion norm reaches zero'], answer: 1, level: 'understand',
      explanation: 'When the middle rotation is +/-90 deg the first and third axes align, so roll and yaw stop being independent coordinates.' },
    { id: 'w4l7q4', question: 'A drone integrates body rates into ZYX Euler attitude at 1 kHz and divides by cos(pitch). Near pitch = 90 deg the estimate diverges. Best fix?',
      choices: ['Raise the loop rate to 8 kHz', 'Clamp pitch at 89 deg and keep Euler angles', 'Integrate an axis-angle theta instead', 'Estimate attitude as a unit quaternion and convert to Euler only for the display layer'], answer: 3, level: 'analyze',
      explanation: 'The singularity is in the Euler chart. A quaternion has no gimbal lock, is cheap to renormalise, and can be converted for display at any time.' },
    { id: 'w4l7q5', question: 'A 2-link arm has a1 = 0.400 m, a2 = 0.300 m, theta1 = 0 deg, theta2 = 90 deg. Where is the end effector?',
      choices: ['(0.700, 0.000) m', '(0.300, 0.400) m', '(0.400, 0.300) m', '(0.212, 0.612) m'], answer: 2, level: 'apply',
      explanation: 'x = 0.400 + 0.300cos(90 deg) = 0.400 m and y = 0.300sin(90 deg) = 0.300 m; the second link is perpendicular to the first.' },
    { id: 'w4l7q6', question: 'Compared with the Denavit-Hartenberg convention, the product of exponentials needs...',
      choices: ['no home configuration', 'one screw axis per joint in the base frame plus the home pose, and no frame-assignment bookkeeping', 'only prismatic joints', 'fewer than four parameters per joint'], answer: 1, level: 'analyze',
      explanation: 'PoE replaces per-link frames with space-frame screw axes and a single home pose M, which matches how URDF stores a joint axis directly.' },
    { id: 'w4l7q7', question: 'You must pick an attitude representation for a 250 Hz flight controller that also logs human-readable angles. Which design?',
      choices: ['Unit quaternion internally with renormalisation each step, Euler converted only for logging', 'ZYX Euler throughout, integrated at 250 Hz', 'Rotation matrix throughout, logging R directly', 'Axis-angle with theta integrated and never renormalised'], answer: 0, level: 'design',
      explanation: 'Quaternion maths is lock-free and cheap; Euler is a lossy display format. Drifting norms must be renormalised, which a fixed-size matrix or Euler triple cannot do cleanly.' },
  ],
  flashcards: [
    { front: 'Frame', back: 'Origin plus three orthonormal axes; a pose is meaningless until its frame is named.', tag: 'frames' },
    { front: 'Right-hand rule', back: 'x cross y = z, and positive rotation about an axis is counter-clockwise sighting down that axis toward the origin.', tag: 'frames' },
    { front: 'SO(3)', back: 'Rotations: R^T R = I, so R^-1 = R^T, and det R = +1. det = -1 is a mirror.', tag: 'rotation' },
    { front: 'Composition order', back: 'R_0^2 = R_0^1 R_1^2; matrix multiplication does not commute, so order encodes the chain.', tag: 'rotation' },
    { front: 'Gimbal lock', back: 'Middle Euler angle hits +/-90 deg, first and third axes align, and the chart loses one coordinate.', tag: 'euler' },
    { front: 'Axis-angle (Rodrigues)', back: 'R = I + sin(theta)[n]x + (1-cos theta)[n]x^2; global, but the axis is undefined at theta = 0.', tag: 'rotation' },
    { front: 'Quaternion double cover', back: 'q and -q are the same rotation; 360 deg returns -q, and 720 deg returns q.', tag: 'quaternion' },
    { front: 'Slerp', back: 'Constant-angular-velocity arc between unit quaternions; flip a sign when q0 dot q1 < 0 to take the short way.', tag: 'quaternion' },
    { front: 'DH parameters', back: 'Four numbers a, alpha, d, theta per joint; theta or d is the joint variable for a revolute or prismatic joint.', tag: 'dh' },
    { front: 'Product of exponentials', back: 'T = exp([S1]theta1)...exp([Sn]thetan) M: space-frame screw axes plus one home pose, no frame bookkeeping.', tag: 'dh' },
  ],
  forgePrompts: [
    'Build a 2-DOF arm from 0.40 m and 0.30 m strips, mark the 0.70 m and 0.10 m reach circles, and check the model against a protractor at theta1 = 30 deg, theta2 = 45 deg.',
    'Log your phone gyro at 100 Hz for 60 s, integrate the rates into a quaternion, and compare with the built-in Euler output as you approach pitch = 90 deg.',
    'Write 20 lines of Python that walks a URDF joint tree and prints the 4x4 tool transform, then diff it against the vendor DH table.',
  ],
};
